/**
 * Token-aware backend functions.
 *
 * Every function listed here declares an optional `token: v.optional(v.string())`
 * argument. The secured Convex client (src/lib/convex-client.ts) injects the
 * current session token into these calls so `withScopeAndEvents` / the engine
 * handlers can resolve the REAL performer server-side from the `sessions`
 * table — making scope checks, audit, timeline and events authoritative.
 *
 * Functions NOT listed here never receive a `token`, so Convex argument
 * validation is never broken by the injection.
 *
 * REGENERATE when new engines adopt the token pattern:
 *   for each file with `token: v.optional(v.string())`, list every
 *   `export const NAME = mutation|query|action({ ... token: v.optional ... }`
 *   as `"<fileBasename>:<NAME>"`.
 */

export const TOKEN_AWARE_FUNCTIONS = new Set<string>([
  // fixedAssetEngine
  "fixedAssetEngine:createAssetCategory",
  "fixedAssetEngine:createFixedAsset",
  "fixedAssetEngine:updateFixedAsset",
  "fixedAssetEngine:calculateDepreciation",
  "fixedAssetEngine:transferAsset",
  "fixedAssetEngine:writeOffAsset",
  "fixedAssetEngine:disposeAsset",
  // inventoryBranchEngine
  "inventoryBranchEngine:adjustStock",
  "inventoryBranchEngine:setStockLocation",
  "inventoryBranchEngine:setStockLimits",
  "inventoryBranchEngine:createTransferRequest",
  "inventoryBranchEngine:approveTransfer",
  "inventoryBranchEngine:reserveStock",
  "inventoryBranchEngine:releaseReservedStock",
  // reportScheduleEngine
  "reportScheduleEngine:createSchedule",
  "reportScheduleEngine:updateSchedule",
  "reportScheduleEngine:toggleSchedule",
  "reportScheduleEngine:deleteSchedule",
  "reportScheduleEngine:saveDashboardLayout",
  "reportScheduleEngine:getUserDashboardLayouts",
  "reportScheduleEngine:getDefaultDashboardLayout",
  // teacherSchedulingEngine
  "teacherSchedulingEngine:assignTeacherSchedule",
  "teacherSchedulingEngine:autoScheduleSubstitute",
  "teacherSchedulingEngine:updateTeacherSettings",
  // communicationHub (communication platform)
  "communicationHub:sendEmail",
  "communicationHub:sendWhatsApp",
  "communicationHub:sendSMS",
  "communicationHub:sendPush",
  "communicationHub:sendInAppNotification",
  "communicationHub:scheduleMessage",
  "communicationHub:cancelScheduledMessage",
  "communicationHub:retryFailedMessage",
  "communicationHub:updateDeliveryStatus",
  "communicationHub:markAsRead",
  "communicationHub:markAllAsRead",
  "communicationHub:togglePin",
  "communicationHub:archiveNotification",
  "communicationHub:deleteNotification",
  "communicationHub:setPreference",
  // crmLeads (lead engine — api.crm.* re-exports these)
  "crmLeads:createLead",
  "crmLeads:updateLead",
  "crmLeads:updateLeadStage",
  "crmLeads:assignLead",
  "crmLeads:deleteLead",
  "crmLeads:bulkAssign",
  "crmLeads:bulkMoveStage",
  "crmLeads:bulkTag",
  "crmLeads:bulkDelete",
  "crmLeads:bulkCreateTasks",
  "crmLeads:importLeads",
  "crmLeads:scheduleFollowup",
  // assignmentEngine (lead assignment engine)
  "assignmentEngine:assignLead",
  "assignmentEngine:reassignLead",
  "assignmentEngine:roundRobinAssign",
  "assignmentEngine:skillBasedAssign",
  "assignmentEngine:branchBasedAssign",
  "assignmentEngine:verticalBasedAssign",
  "assignmentEngine:managerAssign",
  "assignmentEngine:autoAssignLead",
  "assignmentEngine:calculateWorkload",
  "assignmentEngine:createAssignmentRule",
  "assignmentEngine:updateAssignmentRule",
  "assignmentEngine:deleteAssignmentRule",
  // studentEngine
  "studentEngine:createStudent",
  "studentEngine:updateStudent",
  "studentEngine:setParentUser",
  "studentEngine:archiveStudent",
  "studentEngine:restoreStudent",
  // feeEngine
  "feeEngine:createFeeStructure",
  "feeEngine:updateFeeStructure",
  "feeEngine:createFeeAccount",
  "feeEngine:recalculateBalances",
  "feeEngine:generateInstallments",
  "feeEngine:createDiscount",
  "feeEngine:applyDiscount",
  "feeEngine:createScholarship",
  "feeEngine:applyScholarship",
  "feeEngine:createWaiver",
  "feeEngine:approveWaiver",
  "feeEngine:createLateFeeRule",
  "feeEngine:calculateLateFees",
  // financeEngine
  "financeEngine:createJournalEntry",
  "financeEngine:postJournalEntry",
  "financeEngine:reverseJournalEntry",
  "financeEngine:createCashBookEntry",
  "financeEngine:createVendorBill",
  "financeEngine:payVendorBill",
  "financeEngine:createCreditNote",
  "financeEngine:issueCreditNote",
  "financeEngine:applyCreditNoteToInvoice",
  // procurementEngine
  "procurementEngine:createVendor",
  "procurementEngine:updateVendor",
  "procurementEngine:createRequisition",
  "procurementEngine:submitRequisitionForApproval",
  "procurementEngine:approveRequisition",
  "procurementEngine:createPurchaseOrder",
  "procurementEngine:submitPOForApproval",
  "procurementEngine:approvePurchaseOrder",
  "procurementEngine:createGoodsReceipt",
  "procurementEngine:createQuotationComparison",
  "procurementEngine:finalizeQuotationComparison",
  // procurementPlatform (event-pipeline wrappers)
  "procurementPlatform:createVendor",
  "procurementPlatform:updateVendor",
  "procurementPlatform:createRequisition",
  "procurementPlatform:submitRequisitionForApproval",
  "procurementPlatform:approveRequisition",
  "procurementPlatform:createPurchaseOrder",
  "procurementPlatform:submitPOForApproval",
  "procurementPlatform:approvePurchaseOrder",
  "procurementPlatform:createGoodsReceipt",
  "procurementPlatform:createInventoryItem",
  "procurementPlatform:adjustStock",
  "procurementPlatform:issueItem",
  "procurementPlatform:returnIssuedItem",
  "procurementPlatform:allocateAsset",
  "procurementPlatform:returnAsset",
  "procurementPlatform:createPaymentRequest",
  "procurementPlatform:submitPaymentRequest",
  "procurementPlatform:approvePaymentRequest",
  "procurementPlatform:markPaymentPaid",
  "procurementPlatform:createVendorBill",
  // refundEngine
  "refundEngine:createRefundRequest",
  "refundEngine:submitRefundForApproval",
  "refundEngine:approveRefund",
  "refundEngine:processRefund",
  "refundEngine:completeRefund",
  // admissionEngine
  "admissionEngine:createAdmission",
  "admissionEngine:updateAdmissionStatus",
  // documentEngine
  "documentEngine:createFolder",
  "documentEngine:createTag",
  "documentEngine:uploadDocument",
  "documentEngine:updateDocument",
  "documentEngine:createNewVersion",
  "documentEngine:recordDownload",
  "documentEngine:archiveDocument",
  "documentEngine:restoreDocument",
  "documentEngine:setDocumentPermission",
  // userManagement (organization module)
  "userManagement:createUser",
  "userManagement:updateUser",
  "userManagement:disableUser",
  "userManagement:enableUser",
  "userManagement:resetPassword",
  "userManagement:updateUserTeams",
  "userManagement:cloneUserAccess",
  "userManagement:transferUserAccess",
  "userManagement:transferEmployee",
  "userManagement:changeReportingManager",
  "userManagement:updateEmploymentStatus",
  "userManagement:promoteEmployee",
  "userManagement:updateUserScope",
  // employeeLifecycle (HR lifecycle engine)
  "employeeLifecycle:onboardEmployee",
  "employeeLifecycle:confirmEmployee",
  "employeeLifecycle:transferEmployee",
  "employeeLifecycle:promoteEmployee",
  "employeeLifecycle:changeDepartment",
  "employeeLifecycle:assignManager",
  "employeeLifecycle:suspendEmployee",
  "employeeLifecycle:reinstateEmployee",
  "employeeLifecycle:resignEmployee",
  "employeeLifecycle:relieveEmployee",
  "employeeLifecycle:terminateEmployee",
  "employeeLifecycle:retireEmployee",
  // organization (org studio)
  "organization:updateGroup",
  "organization:createDesignation",
  "organization:updateDesignation",
  "organization:deleteDesignation",
  "organization:createDepartment",
  "organization:updateDepartment",
  "organization:deleteDepartment",
  "organization:createCompany",
  "organization:updateCompany",
  "organization:deleteCompany",
  "organization:createBranch",
  "organization:updateBranch",
  "organization:deleteBranch",
  "organization:createTeam",
  "organization:updateTeam",
  "organization:deleteTeam",
  "organization:createVertical",
  "organization:updateVertical",
  "organization:deleteVertical",
  "organization:createSubVertical",
  "organization:updateSubVertical",
  "organization:deleteSubVertical",
  "organization:createBoard",
  "organization:updateBoard",
  "organization:deleteBoard",
  // workflowEngine (workflow studio)
  "workflowEngine:create",
  "workflowEngine:update",
  "workflowEngine:publish",
  "workflowEngine:archive",
  "workflowEngine:remove",
  "workflowEngine:clone",
  "workflowEngine:addNode",
  "workflowEngine:updateNode",
  "workflowEngine:removeNode",
  "workflowEngine:addEdge",
  "workflowEngine:updateEdge",
  "workflowEngine:removeEdge",
  "workflowEngine:startWorkflow",
  "workflowEngine:resumeWorkflow",
  "workflowEngine:cancelInstance",
  "workflowEngine:retryInstance",
  // formEngine (form studio)
  "formEngine:createForm",
  "formEngine:updateForm",
  "formEngine:publishForm",
  "formEngine:archiveForm",
  "formEngine:deactivateForm",
  "formEngine:deleteForm",
  "formEngine:duplicateForm",
  "formEngine:createFormField",
  "formEngine:updateFormField",
  "formEngine:deleteFormField",
  "formEngine:reorderFormFields",
  "formEngine:createSubmission",
  "formEngine:updateSubmissionStatus",
  "formEngine:deleteSubmission",
  // intakeEngine (intake pipeline)
  "intakeEngine:submit",
  "intakeEngine:validate",
  "intakeEngine:deduplicate",
  "intakeEngine:verify",
  "intakeEngine:transform",
  "intakeEngine:route",
  "intakeEngine:completeProcessing",
  "intakeEngine:processSubmission",
  "intakeEngine:routeAndCreateLead",
  "intakeEngine:retrySubmission",
  "intakeEngine:cancelSubmission",
  "intakeEngine:createDuplicateRule",
  "intakeEngine:updateDuplicateRule",
  "intakeEngine:deleteDuplicateRule",
  "intakeEngine:createTransformMapping",
  "intakeEngine:updateTransformMapping",
  "intakeEngine:deleteTransformMapping",
  "intakeEngine:createRoutingRule",
  "intakeEngine:updateRoutingRule",
  "intakeEngine:deleteRoutingRule",
  // lmsPlatform (LMS platform)
  "lmsPlatform:createQuestionBankItem",
  "lmsPlatform:updateQuestionBankItem",
  "lmsPlatform:deleteQuestionBankItem",
  "lmsPlatform:importQuestionsFromBank",
  "lmsPlatform:issueCertificate",
  "lmsPlatform:recordContentUpload",
  "lmsPlatform:deleteContentUpload",
  "lmsPlatform:createCourse",
  "lmsPlatform:publishCourse",
  "lmsPlatform:createLesson",
  "lmsPlatform:publishLesson",
  "lmsPlatform:enrollStudent",
  // slaEngine (CRM SLA engine)
  "slaEngine:createSlaPolicy",
  "slaEngine:updateSlaPolicy",
  "slaEngine:deleteSlaPolicy",
  "slaEngine:startSLA",
  "slaEngine:pauseSLA",
  "slaEngine:resumeSLA",
  "slaEngine:completeSLA",
  "slaEngine:violateSLA",
  "slaEngine:escalateLeadMutation",
  "slaEngine:acknowledgeEscalation",
  "slaEngine:resolveEscalation",
  // lmsEngine (LMS engine)
  "lmsEngine:createCourse",
  "lmsEngine:updateCourse",
  "lmsEngine:publishCourse",
  "lmsEngine:createLesson",
  "lmsEngine:updateLesson",
  "lmsEngine:publishLesson",
  "lmsEngine:createTopic",
  "lmsEngine:updateTopic",
  "lmsEngine:createAnnouncement",
  "lmsEngine:createDiscussion",
  // financePlatform (finance platform)
  "financePlatform:createFeeAccountPlatform",
  "financePlatform:createInvoicePlatform",
  "financePlatform:receivePaymentPlatform",
  "financePlatform:verifyPaymentPlatform",
  "financePlatform:createRefundPlatform",
  "financePlatform:createExpensePlatform",
  "financePlatform:createVendorBillPlatform",
  "financePlatform:createJournalEntryPlatform",
  "financePlatform:approveExpenseWithWorkflow",
  "financePlatform:approveRefundWithWorkflow",
  // recruitmentEngine (recruitment)
  "recruitmentEngine:createJobRequisition",
  "recruitmentEngine:updateJobRequisition",
  "recruitmentEngine:submitForApproval",
  "recruitmentEngine:approveRequisition",
  "recruitmentEngine:cancelRequisition",
  "recruitmentEngine:publishJob",
  "recruitmentEngine:closeJobPosting",
  "recruitmentEngine:applyCandidate",
  "recruitmentEngine:hireCandidate",
  // pdcLegalEngine (PDC legal)
  "pdcLegalEngine:updatePDCLegalStatus",
  "pdcLegalEngine:restrictFutureCheques",
  "pdcLegalEngine:registerNACH",
  "pdcLegalEngine:assignLawyer",
  "pdcLegalEngine:updateCourtStatus",
  "pdcLegalEngine:computeRiskScore",
  "pdcLegalEngine:blacklistStudentCheques",
  "pdcLegalEngine:recordSettlement",
  "pdcLegalEngine:writeOffCheque",
]);
