/**
 * Token-aware backend functions.
 *
 * Every function listed here declares an optional `token: v.optional(v.string())`
 * argument. The secured Convex client (src/lib/convex-client.ts) injects the
 * current session token into these calls so `withScopeAndEvents` / the engine
 * handlers can resolve the REAL performer server-side from the `sessions`
 * table — making scope checks, audit, timeline and events authoritative.
 *
 * Functions NOT listed here never receive a `token`, so Convex argument
 * validation is never broken by the injection.
 *
 * REGENERATE when new engines adopt the token pattern:
 *   for each file with `token: v.optional(v.string())`, list every
 *   `export const NAME = mutation|query|action({ ... token: v.optional ... }`
 *   as `"<fileBasename>:<NAME>"`.
 */

export const TOKEN_AWARE_FUNCTIONS = new Set<string>([
  // fixedAssetEngine
  "fixedAssetEngine:createAssetCategory",
  "fixedAssetEngine:createFixedAsset",
  "fixedAssetEngine:updateFixedAsset",
  "fixedAssetEngine:calculateDepreciation",
  "fixedAssetEngine:transferAsset",
  "fixedAssetEngine:writeOffAsset",
  "fixedAssetEngine:disposeAsset",
  // inventoryBranchEngine
  "inventoryBranchEngine:adjustStock",
  "inventoryBranchEngine:setStockLocation",
  "inventoryBranchEngine:setStockLimits",
  "inventoryBranchEngine:createTransferRequest",
  "inventoryBranchEngine:approveTransfer",
  "inventoryBranchEngine:reserveStock",
  "inventoryBranchEngine:releaseReservedStock",
  // reportScheduleEngine
  "reportScheduleEngine:createSchedule",
  "reportScheduleEngine:updateSchedule",
  "reportScheduleEngine:toggleSchedule",
  "reportScheduleEngine:deleteSchedule",
  "reportScheduleEngine:saveDashboardLayout",
  "reportScheduleEngine:getUserDashboardLayouts",
  "reportScheduleEngine:getDefaultDashboardLayout",
  // teacherSchedulingEngine
  "teacherSchedulingEngine:assignTeacherSchedule",
  "teacherSchedulingEngine:autoScheduleSubstitute",
  "teacherSchedulingEngine:updateTeacherSettings",
  // communicationHub (communication platform)
  "communicationHub:sendEmail",
  "communicationHub:sendWhatsApp",
  "communicationHub:sendSMS",
  "communicationHub:sendPush",
  "communicationHub:sendInAppNotification",
  "communicationHub:scheduleMessage",
  "communicationHub:cancelScheduledMessage",
  "communicationHub:retryFailedMessage",
  "communicationHub:updateDeliveryStatus",
  "communicationHub:markAsRead",
  "communicationHub:markAllAsRead",
  "communicationHub:togglePin",
  "communicationHub:archiveNotification",
  "communicationHub:deleteNotification",
  "communicationHub:setPreference",
  // crmLeads (lead engine — api.crm.* re-exports these)
  "crmLeads:createLead",
  "crmLeads:updateLead",
  "crmLeads:updateLeadStage",
  "crmLeads:assignLead",
  "crmLeads:deleteLead",
  "crmLeads:bulkAssign",
  "crmLeads:bulkMoveStage",
  "crmLeads:bulkTag",
  "crmLeads:bulkDelete",
  "crmLeads:bulkCreateTasks",
  "crmLeads:importLeads",
  "crmLeads:scheduleFollowup",
  // assignmentEngine (lead assignment engine)
  "assignmentEngine:assignLead",
  "assignmentEngine:reassignLead",
  "assignmentEngine:roundRobinAssign",
  "assignmentEngine:skillBasedAssign",
  "assignmentEngine:branchBasedAssign",
  "assignmentEngine:verticalBasedAssign",
  "assignmentEngine:managerAssign",
  "assignmentEngine:autoAssignLead",
  "assignmentEngine:calculateWorkload",
  "assignmentEngine:createAssignmentRule",
  "assignmentEngine:updateAssignmentRule",
  "assignmentEngine:deleteAssignmentRule",
  // studentEngine
  "studentEngine:createStudent",
  "studentEngine:updateStudent",
  "studentEngine:setParentUser",
  "studentEngine:archiveStudent",
  "studentEngine:restoreStudent",
  // feeEngine
  "feeEngine:createFeeStructure",
  "feeEngine:updateFeeStructure",
  "feeEngine:createFeeAccount",
  "feeEngine:recalculateBalances",
  "feeEngine:generateInstallments",
  "feeEngine:createDiscount",
  "feeEngine:applyDiscount",
  "feeEngine:createScholarship",
  "feeEngine:applyScholarship",
  "feeEngine:createWaiver",
  "feeEngine:approveWaiver",
  "feeEngine:createLateFeeRule",
  "feeEngine:calculateLateFees",
  // financeEngine
  "financeEngine:createJournalEntry",
  "financeEngine:postJournalEntry",
  "financeEngine:reverseJournalEntry",
  "financeEngine:createCashBookEntry",
  "financeEngine:createVendorBill",
  "financeEngine:payVendorBill",
  "financeEngine:createCreditNote",
  "financeEngine:issueCreditNote",
  "financeEngine:applyCreditNoteToInvoice",
  // procurementEngine
  "procurementEngine:createVendor",
  "procurementEngine:updateVendor",
  "procurementEngine:createRequisition",
  "procurementEngine:submitRequisitionForApproval",
  "procurementEngine:approveRequisition",
  "procurementEngine:createPurchaseOrder",
  "procurementEngine:submitPOForApproval",
  "procurementEngine:approvePurchaseOrder",
  "procurementEngine:createGoodsReceipt",
  "procurementEngine:createQuotationComparison",
  "procurementEngine:finalizeQuotationComparison",
  // procurementPlatform (event-pipeline wrappers)
  "procurementPlatform:createVendor",
  "procurementPlatform:updateVendor",
  "procurementPlatform:createRequisition",
  "procurementPlatform:submitRequisitionForApproval",
  "procurementPlatform:approveRequisition",
  "procurementPlatform:createPurchaseOrder",
  "procurementPlatform:submitPOForApproval",
  "procurementPlatform:approvePurchaseOrder",
  "procurementPlatform:createGoodsReceipt",
  "procurementPlatform:createInventoryItem",
  "procurementPlatform:adjustStock",
  "procurementPlatform:issueItem",
  "procurementPlatform:returnIssuedItem",
  "procurementPlatform:allocateAsset",
  "procurementPlatform:returnAsset",
  "procurementPlatform:createPaymentRequest",
  "procurementPlatform:submitPaymentRequest",
  "procurementPlatform:approvePaymentRequest",
  "procurementPlatform:markPaymentPaid",
  "procurementPlatform:createVendorBill",
  // refundEngine
  "refundEngine:createRefundRequest",
  "refundEngine:submitRefundForApproval",
  "refundEngine:approveRefund",
  "refundEngine:processRefund",
  "refundEngine:completeRefund",
  // admissionEngine
  "admissionEngine:createAdmission",
  "admissionEngine:updateAdmissionStatus",
  // documentEngine
  "documentEngine:createFolder",
  "documentEngine:createTag",
  "documentEngine:uploadDocument",
  "documentEngine:updateDocument",
  "documentEngine:createNewVersion",
  "documentEngine:recordDownload",
  "documentEngine:archiveDocument",
  "documentEngine:restoreDocument",
  "documentEngine:setDocumentPermission",
  // userManagement (organization module)
  "userManagement:createUser",
  "userManagement:updateUser",
  "userManagement:disableUser",
  "userManagement:enableUser",
  "userManagement:resetPassword",
  "userManagement:updateUserTeams",
  "userManagement:cloneUserAccess",
  "userManagement:transferUserAccess",
  "userManagement:transferEmployee",
  "userManagement:changeReportingManager",
  "userManagement:updateEmploymentStatus",
  "userManagement:promoteEmployee",
  "userManagement:updateUserScope",
  // employeeLifecycle (HR lifecycle engine)
  "employeeLifecycle:onboardEmployee",
  "employeeLifecycle:confirmEmployee",
  "employeeLifecycle:transferEmployee",
  "employeeLifecycle:promoteEmployee",
  "employeeLifecycle:changeDepartment",
  "employeeLifecycle:assignManager",
  "employeeLifecycle:suspendEmployee",
  "employeeLifecycle:reinstateEmployee",
  "employeeLifecycle:resignEmployee",
  "employeeLifecycle:relieveEmployee",
  "employeeLifecycle:terminateEmployee",
  "employeeLifecycle:retireEmployee",
  // organization (org studio)
  "organization:updateGroup",
  "organization:createDesignation",
  "organization:updateDesignation",
  "organization:deleteDesignation",
  "organization:createDepartment",
  "organization:updateDepartment",
  "organization:deleteDepartment",
  "organization:createCompany",
  "organization:updateCompany",
  "organization:deleteCompany",
  "organization:createBranch",
  "organization:updateBranch",
  "organization:deleteBranch",
  "organization:createTeam",
  "organization:updateTeam",
  "organization:deleteTeam",
  "organization:createVertical",
  "organization:updateVertical",
  "organization:deleteVertical",
  "organization:createSubVertical",
  "organization:updateSubVertical",
  "organization:deleteSubVertical",
  "organization:createBoard",
  "organization:updateBoard",
  "organization:deleteBoard",
  // workflowEngine (workflow studio)
  "workflowEngine:create",
  "workflowEngine:update",
  "workflowEngine:publish",
  "workflowEngine:archive",
  "workflowEngine:remove",
  "workflowEngine:clone",
  "workflowEngine:addNode",
  "workflowEngine:updateNode",
  "workflowEngine:removeNode",
  "workflowEngine:addEdge",
  "workflowEngine:updateEdge",
  "workflowEngine:removeEdge",
  "workflowEngine:startWorkflow",
  "workflowEngine:resumeWorkflow",
  "workflowEngine:cancelInstance",
  "workflowEngine:retryInstance",
  // formEngine (form studio)
  "formEngine:createForm",
  "formEngine:updateForm",
  "formEngine:publishForm",
  "formEngine:archiveForm",
  "formEngine:deactivateForm",
  "formEngine:deleteForm",
  "formEngine:duplicateForm",
  "formEngine:createFormField",
  "formEngine:updateFormField",
  "formEngine:deleteFormField",
  "formEngine:reorderFormFields",
  "formEngine:createSubmission",
  "formEngine:updateSubmissionStatus",
  "formEngine:deleteSubmission",
  // intakeEngine (intake pipeline)
  "intakeEngine:submit",
  "intakeEngine:validate",
  "intakeEngine:deduplicate",
  "intakeEngine:verify",
  "intakeEngine:transform",
  "intakeEngine:route",
  "intakeEngine:completeProcessing",
  "intakeEngine:processSubmission",
  "intakeEngine:routeAndCreateLead",
  "intakeEngine:retrySubmission",
  "intakeEngine:cancelSubmission",
  "intakeEngine:createDuplicateRule",
  "intakeEngine:updateDuplicateRule",
  "intakeEngine:deleteDuplicateRule",
  "intakeEngine:createTransformMapping",
  "intakeEngine:updateTransformMapping",
  "intakeEngine:deleteTransformMapping",
  "intakeEngine:createRoutingRule",
  "intakeEngine:updateRoutingRule",
  "intakeEngine:deleteRoutingRule",
  // lmsPlatform (LMS platform)
  "lmsPlatform:createQuestionBankItem",
  "lmsPlatform:updateQuestionBankItem",
  "lmsPlatform:deleteQuestionBankItem",
  "lmsPlatform:importQuestionsFromBank",
  "lmsPlatform:issueCertificate",
  "lmsPlatform:recordContentUpload",
  "lmsPlatform:deleteContentUpload",
  "lmsPlatform:createCourse",
  "lmsPlatform:publishCourse",
  "lmsPlatform:createLesson",
  "lmsPlatform:publishLesson",
  "lmsPlatform:enrollStudent",
  // slaEngine (CRM SLA engine)
  "slaEngine:createSlaPolicy",
  "slaEngine:updateSlaPolicy",
  "slaEngine:deleteSlaPolicy",
  "slaEngine:startSLA",
  "slaEngine:pauseSLA",
  "slaEngine:resumeSLA",
  "slaEngine:completeSLA",
  "slaEngine:violateSLA",
  "slaEngine:escalateLeadMutation",
  "slaEngine:acknowledgeEscalation",
  "slaEngine:resolveEscalation",
  // lmsEngine (LMS engine)
  "lmsEngine:createCourse",
  "lmsEngine:updateCourse",
  "lmsEngine:publishCourse",
  "lmsEngine:createLesson",
  "lmsEngine:updateLesson",
  "lmsEngine:publishLesson",
  "lmsEngine:createTopic",
  "lmsEngine:updateTopic",
  "lmsEngine:createAnnouncement",
  "lmsEngine:createDiscussion",
  // financePlatform (finance platform)
  "financePlatform:createFeeAccountPlatform",
  "financePlatform:createInvoicePlatform",
  "financePlatform:receivePaymentPlatform",
  "financePlatform:verifyPaymentPlatform",
  "financePlatform:createRefundPlatform",
  "financePlatform:createExpensePlatform",
  "financePlatform:createVendorBillPlatform",
  "financePlatform:createJournalEntryPlatform",
  "financePlatform:approveExpenseWithWorkflow",
  "financePlatform:approveRefundWithWorkflow",
  // recruitmentEngine (recruitment)
  "recruitmentEngine:createJobRequisition",
  "recruitmentEngine:updateJobRequisition",
  "recruitmentEngine:submitForApproval",
  "recruitmentEngine:approveRequisition",
  "recruitmentEngine:cancelRequisition",
  "recruitmentEngine:publishJob",
  "recruitmentEngine:closeJobPosting",
  "recruitmentEngine:applyCandidate",
  "recruitmentEngine:hireCandidate",
  // pdcLegalEngine (PDC legal)
  "pdcLegalEngine:updatePDCLegalStatus",
  "pdcLegalEngine:restrictFutureCheques",
  "pdcLegalEngine:registerNACH",
  "pdcLegalEngine:assignLawyer",
  "pdcLegalEngine:updateCourtStatus",
  "pdcLegalEngine:computeRiskScore",
  "pdcLegalEngine:blacklistStudentCheques",
  "pdcLegalEngine:recordSettlement",
  "pdcLegalEngine:writeOffCheque",
  // adminEngine (super admin console)
  "adminEngine:updateSystemConfig",
  "adminEngine:createCompany",
  "adminEngine:createScheduledJob",
  "adminEngine:toggleJob",
  "adminEngine:createApiKey",
  "adminEngine:revokeApiKey",
  "adminEngine:createWebhook",
  "adminEngine:createBackup",
  "adminEngine:completeBackup",
  // marksEngine (exam marks)
  "marksEngine:enterMarks",
  "marksEngine:bulkImportMarks",
  "marksEngine:updateMarks",
  "marksEngine:verifyMarks",
  "marksEngine:moderateMarks",
  "marksEngine:bulkModerateMarks",
  "marksEngine:requestModeration",
  "marksEngine:markAttendance",
  "marksEngine:bulkMarkAttendance",
  // billingEngine (fee invoicing)
  "billingEngine:generateInvoice",
  "billingEngine:cancelInvoice",
  "billingEngine:regenerateInvoice",
  "billingEngine:generateReceipt",
  "billingEngine:generateCreditNote",
  "billingEngine:issueRefund",
  "billingEngine:approveRefund",
  // paymentEngine (fee payments)
  "paymentEngine:createPaymentMethod",
  "paymentEngine:createTaxRule",
  "paymentEngine:receivePayment",
  "paymentEngine:verifyPayment",
  "paymentEngine:reversePayment",
  "paymentEngine:refundPayment",
  "paymentEngine:reconcilePayments",
  // enrollmentEngine (admissions)
  "enrollmentEngine:createStudentFromLead",
  "enrollmentEngine:allocateCourse",
  "enrollmentEngine:assignBatch",
  "enrollmentEngine:assignRollNumber",
  "enrollmentEngine:collectDocument",
  "enrollmentEngine:verifyDocument",
  "enrollmentEngine:completeAdmission",
  "enrollmentEngine:cancelAdmission",
  // academicBatchTypes
  "academicBatchTypes:createAcademicBatchType",
  "academicBatchTypes:updateAcademicBatchType",
  "academicBatchTypes:deleteAcademicBatchType",
  "academicBatchTypes:duplicateAcademicBatchType",
  "academicBatchTypes:reorderAcademicBatchTypes",
  "academicBatchTypes:seedDefaultAcademicBatchTypes",
  // academicBatches
  "academicBatches:createAcademicBatch",
  "academicBatches:updateAcademicBatch",
  "academicBatches:deleteAcademicBatch",
  "academicBatches:duplicateAcademicBatch",
  "academicBatches:reorderAcademicBatches",
  "academicBatches:seedDefaultAcademicBatches",
  // academicBoards
  "academicBoards:createAcademicBoard",
  "academicBoards:updateAcademicBoard",
  "academicBoards:deleteAcademicBoard",
  "academicBoards:duplicateAcademicBoard",
  "academicBoards:reorderAcademicBoards",
  "academicBoards:seedDefaultAcademicBoards",
  // academicClassrooms
  "academicClassrooms:seedDefault",
  "academicClassrooms:create",
  "academicClassrooms:update",
  "academicClassrooms:remove",
  "academicClassrooms:duplicate",
  "academicClassrooms:reorder",
  // academicLanguages
  "academicLanguages:createAcademicLanguage",
  "academicLanguages:updateAcademicLanguage",
  "academicLanguages:deleteAcademicLanguage",
  "academicLanguages:duplicateAcademicLanguage",
  "academicLanguages:reorderAcademicLanguages",
  "academicLanguages:seedDefaultAcademicLanguages",
  // academicMediums
  "academicMediums:createAcademicMedium",
  "academicMediums:updateAcademicMedium",
  "academicMediums:deleteAcademicMedium",
  "academicMediums:duplicateAcademicMedium",
  "academicMediums:reorderAcademicMediums",
  "academicMediums:seedDefaultAcademicMediums",
  // academicPrograms
  "academicPrograms:createAcademicProgram",
  "academicPrograms:updateAcademicProgram",
  "academicPrograms:deleteAcademicProgram",
  "academicPrograms:duplicateAcademicProgram",
  "academicPrograms:reorderAcademicPrograms",
  "academicPrograms:seedDefaultAcademicPrograms",
  // academicSections
  "academicSections:createAcademicSection",
  "academicSections:updateAcademicSection",
  "academicSections:deleteAcademicSection",
  "academicSections:duplicateAcademicSection",
  "academicSections:reorderAcademicSections",
  "academicSections:seedDefaultAcademicSections",
  // academicSemesters
  "academicSemesters:createAcademicSemester",
  "academicSemesters:updateAcademicSemester",
  "academicSemesters:deleteAcademicSemester",
  "academicSemesters:duplicateAcademicSemester",
  "academicSemesters:reorderAcademicSemesters",
  "academicSemesters:seedDefaultAcademicSemesters",
  // academicSessions
  "academicSessions:createAcademicSession",
  "academicSessions:updateAcademicSession",
  "academicSessions:deleteAcademicSession",
  "academicSessions:duplicateAcademicSession",
  "academicSessions:reorderAcademicSessions",
  "academicSessions:seedDefaultAcademicSessions",
  // academicStreams
  "academicStreams:createAcademicStream",
  "academicStreams:updateAcademicStream",
  "academicStreams:deleteAcademicStream",
  "academicStreams:duplicateAcademicStream",
  "academicStreams:reorderAcademicStreams",
  "academicStreams:seedDefaultAcademicStreams",
  // academicSubVerticals
  "academicSubVerticals:createAcademicSubVertical",
  "academicSubVerticals:updateAcademicSubVertical",
  "academicSubVerticals:deleteAcademicSubVertical",
  "academicSubVerticals:duplicateAcademicSubVertical",
  "academicSubVerticals:reorderAcademicSubVerticals",
  "academicSubVerticals:seedDefaultAcademicSubVerticals",
  // academicSubjects
  "academicSubjects:createAcademicSubject",
  "academicSubjects:updateAcademicSubject",
  "academicSubjects:deleteAcademicSubject",
  "academicSubjects:duplicateAcademicSubject",
  "academicSubjects:reorderAcademicSubjects",
  "academicSubjects:seedDefaultAcademicSubjects",
  // academicTerms
  "academicTerms:createAcademicTerm",
  "academicTerms:updateAcademicTerm",
  "academicTerms:deleteAcademicTerm",
  "academicTerms:duplicateAcademicTerm",
  "academicTerms:reorderAcademicTerms",
  "academicTerms:seedDefaultAcademicTerms",
  // academicVerticals
  "academicVerticals:createAcademicVertical",
  "academicVerticals:updateAcademicVertical",
  "academicVerticals:deleteAcademicVertical",
  "academicVerticals:duplicateAcademicVertical",
  "academicVerticals:reorderAcademicVerticals",
  "academicVerticals:seedDefaultAcademicVerticals",
  // crmCampaignChannels
  "crmCampaignChannels:createCampaignChannel",
  "crmCampaignChannels:updateCampaignChannel",
  "crmCampaignChannels:deleteCampaignChannel",
  "crmCampaignChannels:duplicateCampaignChannel",
  "crmCampaignChannels:reorderCampaignChannels",
  "crmCampaignChannels:seedDefaultChannels",
  // crmCampaignTypes
  "crmCampaignTypes:createCampaignType",
  "crmCampaignTypes:updateCampaignType",
  "crmCampaignTypes:deleteCampaignType",
  "crmCampaignTypes:duplicateCampaignType",
  "crmCampaignTypes:reorderCampaignTypes",
  "crmCampaignTypes:seedDefaultTypes",
  // crmCounsellingOutcomes
  "crmCounsellingOutcomes:seedDefault",
  "crmCounsellingOutcomes:createCounsellingOutcome",
  "crmCounsellingOutcomes:updateCounsellingOutcome",
  "crmCounsellingOutcomes:deleteCounsellingOutcome",
  "crmCounsellingOutcomes:duplicateCounsellingOutcome",
  "crmCounsellingOutcomes:reorderCounsellingOutcomes",
  // crmCounsellingTypes
  "crmCounsellingTypes:seedDefault",
  "crmCounsellingTypes:createCounsellingType",
  "crmCounsellingTypes:updateCounsellingType",
  "crmCounsellingTypes:deleteCounsellingType",
  "crmCounsellingTypes:duplicateCounsellingType",
  "crmCounsellingTypes:reorderCounsellingTypes",
  // crmCourses
  "crmCourses:createCourse",
  "crmCourses:updateCourse",
  "crmCourses:duplicateCourse",
  "crmCourses:addCourseToLead",
  "crmCourses:removeCourseFromLead",
  // crmEnquiryTypes
  "crmEnquiryTypes:createEnquiryType",
  "crmEnquiryTypes:updateEnquiryType",
  "crmEnquiryTypes:deleteEnquiryType",
  "crmEnquiryTypes:duplicateEnquiryType",
  "crmEnquiryTypes:reorderEnquiryTypes",
  "crmEnquiryTypes:seedDefaultEnquiryTypes",
  // crmFollowUpOutcomes
  "crmFollowUpOutcomes:createFollowUpOutcome",
  "crmFollowUpOutcomes:updateFollowUpOutcome",
  "crmFollowUpOutcomes:deleteFollowUpOutcome",
  "crmFollowUpOutcomes:duplicateFollowUpOutcome",
  "crmFollowUpOutcomes:reorderFollowUpOutcomes",
  "crmFollowUpOutcomes:seedDefaultFollowUpOutcomes",
  // crmFollowUpTypes
  "crmFollowUpTypes:createFollowUpType",
  "crmFollowUpTypes:updateFollowUpType",
  "crmFollowUpTypes:deleteFollowUpType",
  "crmFollowUpTypes:duplicateFollowUpType",
  "crmFollowUpTypes:reorderFollowUpTypes",
  "crmFollowUpTypes:seedDefaultFollowUpTypes",
  // crmIndustries
  "crmIndustries:seedDefault",
  "crmIndustries:create",
  "crmIndustries:update",
  "crmIndustries:remove",
  "crmIndustries:duplicate",
  "crmIndustries:reorder",
  // crmLeadCategories
  "crmLeadCategories:seedDefault",
  "crmLeadCategories:createLeadCategory",
  "crmLeadCategories:updateLeadCategory",
  "crmLeadCategories:deleteLeadCategory",
  "crmLeadCategories:duplicateLeadCategory",
  "crmLeadCategories:reorderLeadCategories",
  // crmLeadQualification
  "crmLeadQualification:seedDefault",
  "crmLeadQualification:createLeadQualification",
  "crmLeadQualification:updateLeadQualification",
  "crmLeadQualification:deleteLeadQualification",
  "crmLeadQualification:duplicateLeadQualification",
  "crmLeadQualification:reorderLeadQualifications",
  // crmLeadScoringRules
  "crmLeadScoringRules:seedDefault",
  "crmLeadScoringRules:createLeadScoringRule",
  "crmLeadScoringRules:updateLeadScoringRule",
  "crmLeadScoringRules:deleteLeadScoringRule",
  "crmLeadScoringRules:duplicateLeadScoringRule",
  "crmLeadScoringRules:reorderLeadScoringRules",
  // crmLostReasons
  "crmLostReasons:createLostReason",
  "crmLostReasons:updateLostReason",
  "crmLostReasons:deleteLostReason",
  "crmLostReasons:duplicateLostReason",
  "crmLostReasons:reorderLostReasons",
  "crmLostReasons:seedDefaultLostReasons",
  // crmMarketingChannels
  "crmMarketingChannels:createMarketingChannel",
  "crmMarketingChannels:updateMarketingChannel",
  "crmMarketingChannels:deleteMarketingChannel",
  "crmMarketingChannels:duplicateMarketingChannel",
  "crmMarketingChannels:reorderMarketingChannels",
  "crmMarketingChannels:seedDefaultMarketingChannels",
  // crmPriorities
  "crmPriorities:createPriority",
  "crmPriorities:updatePriority",
  "crmPriorities:deletePriority",
  "crmPriorities:duplicatePriority",
  "crmPriorities:reorderPriorities",
  "crmPriorities:seedDefaultPriorities",
  // crmReferralSources
  "crmReferralSources:seedDefault",
  "crmReferralSources:createReferralSource",
  "crmReferralSources:updateReferralSource",
  "crmReferralSources:deleteReferralSource",
  "crmReferralSources:duplicateReferralSource",
  "crmReferralSources:reorderReferralSources",
  // crmSources
  "crmSources:createSource",
  "crmSources:updateSource",
  "crmSources:deleteSource",
  "crmSources:duplicateSource",
  "crmSources:reorderSources",
  "crmSources:seedDefaultSources",
  // crmStages
  "crmStages:createStage",
  "crmStages:updateStage",
  "crmStages:deleteStage",
  "crmStages:duplicateStage",
  "crmStages:reorderStages",
  "crmStages:seedDefaultStages",
  // crmTags
  "crmTags:createTag",
  "crmTags:updateTag",
  "crmTags:deleteTag",
  "crmTags:duplicateTag",
  "crmTags:reorderTags",
  "crmTags:seedDefaultTags",
  // crmUtmCampaigns
  "crmUtmCampaigns:createUtmCampaign",
  "crmUtmCampaigns:updateUtmCampaign",
  "crmUtmCampaigns:deleteUtmCampaign",
  "crmUtmCampaigns:duplicateUtmCampaign",
  "crmUtmCampaigns:reorderUtmCampaigns",
  "crmUtmCampaigns:seedDefaultUtmCampaigns",
  // crmUtmMediums
  "crmUtmMediums:createUtmMedium",
  "crmUtmMediums:updateUtmMedium",
  "crmUtmMediums:deleteUtmMedium",
  "crmUtmMediums:duplicateUtmMedium",
  "crmUtmMediums:reorderUtmMediums",
  "crmUtmMediums:seedDefaultUtmMediums",
  // crmUtmSources
  "crmUtmSources:createUtmSource",
  "crmUtmSources:updateUtmSource",
  "crmUtmSources:deleteUtmSource",
  "crmUtmSources:duplicateUtmSource",
  "crmUtmSources:reorderUtmSources",
  "crmUtmSources:seedDefaultUtmSources",
  // financeBankAccounts
  "financeBankAccounts:seedDefault",
  "financeBankAccounts:create",
  "financeBankAccounts:update",
  "financeBankAccounts:remove",
  "financeBankAccounts:duplicate",
  "financeBankAccounts:reorder",
  // financeCurrencies
  "financeCurrencies:seedDefault",
  "financeCurrencies:create",
  "financeCurrencies:update",
  "financeCurrencies:remove",
  "financeCurrencies:duplicate",
  "financeCurrencies:reorder",
  // financeDiscountCategories
  "financeDiscountCategories:seedDefault",
  "financeDiscountCategories:create",
  "financeDiscountCategories:update",
  "financeDiscountCategories:remove",
  "financeDiscountCategories:duplicate",
  "financeDiscountCategories:reorder",
  // financeExpenseCategories
  "financeExpenseCategories:seedDefault",
  "financeExpenseCategories:create",
  "financeExpenseCategories:update",
  "financeExpenseCategories:remove",
  "financeExpenseCategories:duplicate",
  "financeExpenseCategories:reorder",
  // financeFeeCategories
  "financeFeeCategories:seedDefault",
  "financeFeeCategories:create",
  "financeFeeCategories:update",
  "financeFeeCategories:remove",
  "financeFeeCategories:duplicate",
  "financeFeeCategories:reorder",
  // financeFinancialYears
  "financeFinancialYears:seedDefault",
  "financeFinancialYears:create",
  "financeFinancialYears:update",
  "financeFinancialYears:remove",
  "financeFinancialYears:duplicate",
  "financeFinancialYears:reorder",
  // financeGstRates
  "financeGstRates:seedDefault",
  "financeGstRates:create",
  "financeGstRates:update",
  "financeGstRates:remove",
  "financeGstRates:duplicate",
  "financeGstRates:reorder",
  // financeIncomeCategories
  "financeIncomeCategories:seedDefault",
  "financeIncomeCategories:create",
  "financeIncomeCategories:update",
  "financeIncomeCategories:remove",
  "financeIncomeCategories:duplicate",
  "financeIncomeCategories:reorder",
  // financePaymentModes
  "financePaymentModes:seedDefault",
  "financePaymentModes:create",
  "financePaymentModes:update",
  "financePaymentModes:remove",
  "financePaymentModes:duplicate",
  "financePaymentModes:reorder",
  // financeTaxTypes
  "financeTaxTypes:seedDefault",
  "financeTaxTypes:create",
  "financeTaxTypes:update",
  "financeTaxTypes:remove",
  "financeTaxTypes:duplicate",
  "financeTaxTypes:reorder",
  // hrDocumentTypes
  "hrDocumentTypes:seedDefault",
  "hrDocumentTypes:create",
  "hrDocumentTypes:update",
  "hrDocumentTypes:remove",
  "hrDocumentTypes:duplicate",
  "hrDocumentTypes:reorder",
  // hrEmployeeCategories
  "hrEmployeeCategories:seedDefault",
  "hrEmployeeCategories:create",
  "hrEmployeeCategories:update",
  "hrEmployeeCategories:remove",
  "hrEmployeeCategories:duplicate",
  "hrEmployeeCategories:reorder",
  // hrEmployeeTypes
  "hrEmployeeTypes:createEmployeeType",
  "hrEmployeeTypes:updateEmployeeType",
  "hrEmployeeTypes:deleteEmployeeType",
  "hrEmployeeTypes:duplicateEmployeeType",
  "hrEmployeeTypes:reorderEmployeeTypes",
  "hrEmployeeTypes:seedDefaultEmployeeTypes",
  // hrEmploymentStatuses
  "hrEmploymentStatuses:createEmploymentStatus",
  "hrEmploymentStatuses:updateEmploymentStatus",
  "hrEmploymentStatuses:deleteEmploymentStatus",
  "hrEmploymentStatuses:duplicateEmploymentStatus",
  "hrEmploymentStatuses:reorderEmploymentStatuses",
  "hrEmploymentStatuses:seedDefaultEmploymentStatuses",
  // hrExperienceLevels
  "hrExperienceLevels:seedDefault",
  "hrExperienceLevels:create",
  "hrExperienceLevels:update",
  "hrExperienceLevels:remove",
  "hrExperienceLevels:duplicate",
  "hrExperienceLevels:reorder",
  // hrSkills
  "hrSkills:seedDefault",
  "hrSkills:create",
  "hrSkills:update",
  "hrSkills:remove",
  "hrSkills:duplicate",
  "hrSkills:reorder",
  // hrWorkLocations
  "hrWorkLocations:seedDefault",
  "hrWorkLocations:create",
  "hrWorkLocations:update",
  "hrWorkLocations:remove",
  "hrWorkLocations:duplicate",
  "hrWorkLocations:reorder",
  // organizationBranches
  "organizationBranches:createBranch",
  "organizationBranches:updateBranch",
  "organizationBranches:deleteBranch",
  "organizationBranches:duplicateBranch",
  "organizationBranches:reorderBranches",
  "organizationBranches:seedDefaultBranches",
  // organizationCompanies
  "organizationCompanies:createCompany",
  "organizationCompanies:updateCompany",
  "organizationCompanies:deleteCompany",
  "organizationCompanies:duplicateCompany",
  "organizationCompanies:reorderCompanies",
  "organizationCompanies:seedDefaultCompanies",
  // organizationDepartments
  "organizationDepartments:createDepartment",
  "organizationDepartments:updateDepartment",
  "organizationDepartments:deleteDepartment",
  "organizationDepartments:duplicateDepartment",
  "organizationDepartments:reorderDepartments",
  "organizationDepartments:seedDefaultDepartments",
  // organizationDesignations
  "organizationDesignations:createDesignation",
  "organizationDesignations:updateDesignation",
  "organizationDesignations:deleteDesignation",
  "organizationDesignations:duplicateDesignation",
  "organizationDesignations:reorderDesignations",
  "organizationDesignations:seedDefaultDesignations",
  // organizationTeams
  "organizationTeams:createTeam",
  "organizationTeams:updateTeam",
  "organizationTeams:deleteTeam",
  "organizationTeams:duplicateTeam",
  "organizationTeams:reorderTeams",
  "organizationTeams:seedDefaultTeams",
]);
