import { defineTable } from "convex/server";
import { v } from "convex/values";

export const academicTables = {
  academicBatchTypes: defineTable({
    name: v.string(),
    code: v.string(),
    deliveryMode: v.string(),
    timingCategory: v.string(),
    description: v.optional(v.string()),
    displayOrder: v.number(),
    color: v.string(),
    icon: v.string(),
    isActive: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("displayOrder", ["displayOrder"])
    .index("by_active", ["isActive"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  academicBatches: defineTable({
    name: v.string(),
    code: v.string(),
    programId: v.id("academicPrograms"),
    batchTypeId: v.id("academicBatchTypes"),
    academicSessionId: v.id("academicSessions"),
    capacity: v.optional(v.number()),
    minStrength: v.optional(v.number()),
    maxStrength: v.optional(v.number()),
    startDate: v.optional(v.number()),
    endDate: v.optional(v.number()),
    description: v.optional(v.string()),
    sequence: v.number(),
    color: v.string(),
    icon: v.string(),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("sequence", ["sequence"])
    .index("programId", ["programId"])
    .index("batchTypeId", ["batchTypeId"])
    .index("academicSessionId", ["academicSessionId"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  academicBoards: defineTable({
    name: v.string(),
    code: v.string(),
    shortName: v.string(),
    color: v.string(),
    icon: v.string(),
    country: v.string(),
    educationLevel: v.string(),
    website: v.optional(v.string()),
    description: v.optional(v.string()),
    displayOrder: v.number(),
    isActive: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("displayOrder", ["displayOrder"])
    .index("by_active", ["isActive"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  academicClassrooms: defineTable({
    name: v.string(),
    code: v.string(),
    building: v.optional(v.string()),
    floor: v.optional(v.number()),
    roomNumber: v.optional(v.string()),
    capacity: v.optional(v.number()),
    hasMultimedia: v.boolean(),
    hasAirConditioning: v.boolean(),
    description: v.optional(v.string()),
    color: v.string(),
    icon: v.string(),
    sequence: v.number(),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("sequence", ["sequence"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  academicLanguages: defineTable({
    name: v.string(),
    code: v.string(),
    isoCode: v.string(),
    nativeName: v.optional(v.string()),
    description: v.optional(v.string()),
    color: v.string(),
    icon: v.string(),
    isRTL: v.boolean(),
    sequence: v.number(),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("sequence", ["sequence"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  academicMediums: defineTable({
    name: v.string(),
    code: v.string(),
    description: v.optional(v.string()),
    color: v.string(),
    icon: v.string(),
    sequence: v.number(),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("sequence", ["sequence"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  academicPrograms: defineTable({
    subVerticalId: v.id("academicSubVerticals"),
    name: v.string(),
    code: v.string(),
    programType: v.string(),
    duration: v.number(),
    durationUnit: v.string(),
    deliveryMode: v.string(),
    description: v.optional(v.string()),
    displayOrder: v.number(),
    color: v.string(),
    icon: v.string(),
    isActive: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("displayOrder", ["displayOrder"])
    .index("subVerticalId", ["subVerticalId"])
    .index("by_active", ["isActive"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  academicSections: defineTable({
    name: v.string(),
    code: v.string(),
    description: v.optional(v.string()),
    color: v.string(),
    icon: v.string(),
    sequence: v.number(),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("sequence", ["sequence"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  academicSemesters: defineTable({
    name: v.string(),
    code: v.string(),
    academicSessionId: v.id("academicSessions"),
    semesterNumber: v.number(),
    startDate: v.optional(v.number()),
    endDate: v.optional(v.number()),
    description: v.optional(v.string()),
    color: v.string(),
    icon: v.string(),
    sequence: v.number(),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("sequence", ["sequence"])
    .index("academicSessionId", ["academicSessionId"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  academicSessions: defineTable({
    name: v.string(),
    code: v.string(),
    academicYear: v.string(),
    color: v.string(),
    icon: v.string(),
    startDate: v.number(),
    endDate: v.number(),
    admissionStartDate: v.optional(v.number()),
    admissionEndDate: v.optional(v.number()),
    description: v.optional(v.string()),
    sequence: v.number(),
    isCurrent: v.boolean(),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("sequence", ["sequence"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  academicStreams: defineTable({
    name: v.string(),
    code: v.string(),
    educationLevel: v.string(),
    description: v.optional(v.string()),
    color: v.string(),
    icon: v.string(),
    sequence: v.number(),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("sequence", ["sequence"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  academicSubVerticals: defineTable({
    verticalId: v.id("academicVerticals"),
    name: v.string(),
    code: v.string(),
    color: v.string(),
    icon: v.string(),
    description: v.optional(v.string()),
    displayOrder: v.number(),
    isActive: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("displayOrder", ["displayOrder"])
    .index("verticalId", ["verticalId"])
    .index("by_active", ["isActive"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  academicSubjects: defineTable({
    name: v.string(),
    code: v.string(),
    category: v.string(),
    subjectType: v.string(),
    description: v.optional(v.string()),
    displayOrder: v.number(),
    color: v.string(),
    icon: v.string(),
    isTheory: v.boolean(),
    isPractical: v.boolean(),
    isActive: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("displayOrder", ["displayOrder"])
    .index("category", ["category"])
    .index("by_active", ["isActive"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  academicTerms: defineTable({
    name: v.string(),
    code: v.string(),
    academicSessionId: v.id("academicSessions"),
    termNumber: v.number(),
    startDate: v.optional(v.number()),
    endDate: v.optional(v.number()),
    description: v.optional(v.string()),
    color: v.string(),
    icon: v.string(),
    sequence: v.number(),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("sequence", ["sequence"])
    .index("academicSessionId", ["academicSessionId"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  academicVerticals: defineTable({
    name: v.string(),
    code: v.string(),
    color: v.string(),
    icon: v.string(),
    educationCategory: v.string(),
    description: v.optional(v.string()),
    minimumAge: v.optional(v.number()),
    maximumAge: v.optional(v.number()),
    displayOrder: v.number(),
    isActive: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("displayOrder", ["displayOrder"])
    .index("by_active", ["isActive"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
};