import { defineTable } from "convex/server";
import { v } from "convex/values";

export const communicationTables = {
  channelMembers: defineTable({
    channelId: v.id("channels"),
    userId: v.id("users"),
    joinedAt: v.number(),
    lastReadAt: v.optional(v.number()),
  }),
  channels: defineTable({
    name: v.string(),
    description: v.optional(v.string()),
    type: v.union(v.literal("channel"), v.literal("announcement")),
    createdBy: v.id("users"),
    isArchived: v.optional(v.boolean()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("type", ["type"])
    .index("createdBy", ["createdBy"]),
  commEmailTemplates: defineTable({
    name: v.string(),
    code: v.string(),
    templateCategory: v.string(),
    subject: v.string(),
    bodyPreview: v.optional(v.string()),
    description: v.optional(v.string()),
    color: v.string(),
    icon: v.string(),
    sequence: v.number(),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("sequence", ["sequence"]),
  commNotificationTypes: defineTable({
    name: v.string(),
    code: v.string(),
    channelType: v.string(),
    description: v.optional(v.string()),
    color: v.string(),
    icon: v.string(),
    sequence: v.number(),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("sequence", ["sequence"]),
  commSmsTemplates: defineTable({
    name: v.string(),
    code: v.string(),
    templateCategory: v.string(),
    bodyPreview: v.optional(v.string()),
    description: v.optional(v.string()),
    color: v.string(),
    icon: v.string(),
    sequence: v.number(),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("sequence", ["sequence"]),
  commWhatsAppTemplates: defineTable({
    name: v.string(),
    code: v.string(),
    templateCategory: v.string(),
    bodyPreview: v.optional(v.string()),
    description: v.optional(v.string()),
    color: v.string(),
    icon: v.string(),
    sequence: v.number(),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("sequence", ["sequence"]),
  communicationLogs: defineTable({
    queueId: v.id("communicationQueue"),
    action: v.string(),
    status: v.string(),
    details: v.optional(v.string()),
    metadata: v.optional(v.string()),
    performedAt: v.number(),
  })
    .index("queueId", ["queueId"])
    .index("queueId_performedAt", ["queueId", "performedAt"]),
  communicationPreferences: defineTable({
    userId: v.optional(v.id("users")),
    entityType: v.optional(v.string()),
    entityId: v.optional(v.string()),
    channel: v.union(v.literal("email"), v.literal("whatsapp"), v.literal("sms"), v.literal("push"), v.literal("in_app")),
    category: v.string(),
    enabled: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("userId_category", ["userId", "category"])
    .index("entityType", ["entityType"]),
  communicationQueue: defineTable({
    templateId: v.optional(v.id("communicationTemplates")),
    channel: v.union(v.literal("email"), v.literal("whatsapp"), v.literal("sms"), v.literal("push"), v.literal("in_app")),
    recipientId: v.optional(v.string()),
    recipientType: v.optional(v.string()),
    recipientAddress: v.string(),
    recipientName: v.optional(v.string()),
    subject: v.optional(v.string()),
    body: v.string(),
    variables: v.optional(v.string()),
    status: v.union(
      v.literal("queued"), v.literal("processing"),
      v.literal("sent"), v.literal("delivered"),
      v.literal("read"), v.literal("failed"),
      v.literal("retrying"), v.literal("cancelled"),
    ),
    priority: v.union(v.literal("low"), v.literal("normal"), v.literal("high"), v.literal("urgent")),
    scheduledAt: v.optional(v.number()),
    sentAt: v.optional(v.number()),
    deliveredAt: v.optional(v.number()),
    readAt: v.optional(v.number()),
    failedAt: v.optional(v.number()),
    errorMessage: v.optional(v.string()),
    retryCount: v.number(),
    maxRetries: v.number(),
    campaignId: v.optional(v.id("messageCampaigns")),
    referenceType: v.optional(v.string()),
    referenceId: v.optional(v.string()),
    createdBy: v.optional(v.id("users")),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("recipientId", ["recipientId"])
    .index("campaignId", ["campaignId"])
    .index("referenceType", ["referenceType"]),
  communicationTemplates: defineTable({
    name: v.string(),
    code: v.string(),
    description: v.optional(v.string()),
    channel: v.union(v.literal("email"), v.literal("whatsapp"), v.literal("sms"), v.literal("push"), v.literal("in_app")),
    subject: v.optional(v.string()),
    body: v.string(),
    variables: v.optional(v.array(v.string())),
    category: v.optional(v.string()),
    isActive: v.boolean(),
    isSystem: v.boolean(),
    createdBy: v.optional(v.id("users")),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("code", ["code"])
    .index("category", ["category"])
    .index("isActive", ["isActive"]),
  directMessages: defineTable({
    senderId: v.id("users"),
    receiverId: v.id("users"),
    content: v.string(),
    isRead: v.boolean(),
    createdAt: v.number(),
  })
    .index("receiverId", ["receiverId"])
    .index("participants", ["senderId", "receiverId"]),
  messageCampaigns: defineTable({
    name: v.string(),
    description: v.optional(v.string()),
    channel: v.union(v.literal("email"), v.literal("whatsapp"), v.literal("sms"), v.literal("push")),
    templateId: v.optional(v.id("communicationTemplates")),
    targetType: v.string(),
    targetFilter: v.optional(v.string()),
    totalRecipients: v.number(),
    sentCount: v.number(),
    deliveredCount: v.number(),
    readCount: v.number(),
    failedCount: v.number(),
    status: v.union(v.literal("draft"), v.literal("scheduled"), v.literal("running"), v.literal("completed"), v.literal("paused"), v.literal("cancelled"), v.literal("failed")),
    scheduledAt: v.optional(v.number()),
    startedAt: v.optional(v.number()),
    completedAt: v.optional(v.number()),
    createdBy: v.optional(v.id("users")),
    createdAt: v.number(),
    updatedAt: v.number(),
  }),
  messages: defineTable({
    channelId: v.id("channels"),
    senderId: v.id("users"),
    content: v.string(),
    parentId: v.optional(v.id("messages")),
    isPinned: v.optional(v.boolean()),
    mentions: v.optional(v.array(v.id("users"))),
    createdAt: v.number(),
    updatedAt: v.optional(v.number()),
  })
    .index("channelId_createdAt", ["channelId", "createdAt"]),
};