import { defineTable } from "convex/server";
import { v } from "convex/values";

export const crmTables = {
  callLogs: defineTable({
    leadId: v.id("leadMaster"),
    callType: v.string(),
    outcome: v.string(),
    callDate: v.number(),
    durationMinutes: v.optional(v.number()),
    durationSeconds: v.optional(v.number()),
    notes: v.optional(v.string()),
    followupDate: v.optional(v.number()),
    createFollowupTask: v.boolean(),
    userId: v.id("users"),
    createdAt: v.number(),
  })
    .index("leadId", ["leadId"])
    .index("by_user", ["userId"])
    .index("by_created", ["createdAt"]),
  courses: defineTable({
    courseCode: v.string(),
    courseName: v.string(),
    verticalId: v.optional(v.id("verticals")),
    subVerticalId: v.optional(v.id("subVerticals")),
    boardId: v.optional(v.id("boards")),
    baseFee: v.number(),
    description: v.optional(v.string()),
    status: v.union(v.literal("active"), v.literal("archived"), v.literal("draft")),
    createdBy: v.id("users"),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("courseCode", ["courseCode"])
    .index("verticalId", ["verticalId"])
    .index("status", ["status"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  crmCampaignChannels: defineTable({
    name: v.string(),
    code: v.string(),
    channelCategory: v.string(),
    isDigital: v.boolean(),
    description: v.optional(v.string()),
    color: v.string(),
    icon: v.string(),
    sequence: v.number(),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("sequence", ["sequence"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  crmCampaignTypes: defineTable({
    name: v.string(),
    code: v.string(),
    campaignCategory: v.string(),
    description: v.optional(v.string()),
    color: v.string(),
    icon: v.string(),
    sequence: v.number(),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("sequence", ["sequence"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  crmCounsellingOutcomes: defineTable({
    name: v.string(),
    code: v.string(),
    outcomeCategory: v.string(),
    recommendedAction: v.optional(v.string()),
    description: v.optional(v.string()),
    color: v.string(),
    icon: v.string(),
    sequence: v.number(),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("sequence", ["sequence"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  crmCounsellingTypes: defineTable({
    name: v.string(),
    code: v.string(),
    counsellingMode: v.string(),
    durationMinutes: v.optional(v.number()),
    description: v.optional(v.string()),
    color: v.string(),
    icon: v.string(),
    sequence: v.number(),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("sequence", ["sequence"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  crmEnquiryTypes: defineTable({
    name: v.string(),
    code: v.string(),
    educationCategory: v.string(),
    description: v.optional(v.string()),
    color: v.string(),
    icon: v.string(),
    sequence: v.number(),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("sequence", ["sequence"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  crmFollowUpOutcomes: defineTable({
    name: v.string(),
    code: v.string(),
    outcomeCategory: v.string(),
    movesPipeline: v.boolean(),
    isPositive: v.boolean(),
    description: v.optional(v.string()),
    color: v.string(),
    icon: v.string(),
    sequence: v.number(),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("sequence", ["sequence"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  crmFollowUpTypes: defineTable({
    name: v.string(),
    code: v.string(),
    followUpCategory: v.string(),
    requiresReminder: v.boolean(),
    defaultReminderDays: v.optional(v.number()),
    description: v.optional(v.string()),
    color: v.string(),
    icon: v.string(),
    sequence: v.number(),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("sequence", ["sequence"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  crmIndustries: defineTable({
    name: v.string(),
    code: v.string(),
    sector: v.string(),
    description: v.optional(v.string()),
    color: v.string(),
    icon: v.string(),
    sequence: v.number(),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("sequence", ["sequence"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  crmLeadCategories: defineTable({
    name: v.string(),
    code: v.string(),
    categoryType: v.string(),
    description: v.optional(v.string()),
    color: v.string(),
    icon: v.string(),
    sequence: v.number(),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("sequence", ["sequence"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  crmLeadQualification: defineTable({
    name: v.string(),
    code: v.string(),
    minimumScore: v.optional(v.number()),
    maximumScore: v.optional(v.number()),
    description: v.optional(v.string()),
    color: v.string(),
    icon: v.string(),
    sequence: v.number(),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("sequence", ["sequence"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  crmLeadScoringRules: defineTable({
    name: v.string(),
    code: v.string(),
    scoreValue: v.number(),
    ruleCategory: v.string(),
    description: v.optional(v.string()),
    color: v.string(),
    icon: v.string(),
    sequence: v.number(),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("sequence", ["sequence"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  crmLostReasons: defineTable({
    name: v.string(),
    code: v.string(),
    description: v.optional(v.string()),
    color: v.string(),
    icon: v.string(),
    sequence: v.number(),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("sequence", ["sequence"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  crmMarketingChannels: defineTable({
    name: v.string(),
    code: v.string(),
    marketingType: v.string(),
    isOnline: v.boolean(),
    description: v.optional(v.string()),
    color: v.string(),
    icon: v.string(),
    sequence: v.number(),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("sequence", ["sequence"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  crmPriorities: defineTable({
    name: v.string(),
    code: v.string(),
    description: v.optional(v.string()),
    color: v.string(),
    icon: v.string(),
    sequence: v.number(),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("sequence", ["sequence"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  crmReferralSources: defineTable({
    name: v.string(),
    code: v.string(),
    referralCategory: v.string(),
    rewardEligible: v.boolean(),
    description: v.optional(v.string()),
    color: v.string(),
    icon: v.string(),
    sequence: v.number(),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("sequence", ["sequence"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  crmSources: defineTable({
    name: v.string(),
    code: v.string(),
    description: v.optional(v.string()),
    color: v.string(),
    icon: v.string(),
    sequence: v.number(),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("sequence", ["sequence"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  crmStages: defineTable({
    name: v.string(),
    color: v.string(),
    icon: v.string(),
    probability: v.number(),
    sequence: v.number(),
    description: v.optional(v.string()),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("sequence", ["sequence"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  crmTags: defineTable({
    name: v.string(),
    code: v.string(),
    description: v.optional(v.string()),
    color: v.string(),
    icon: v.string(),
    sequence: v.number(),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("sequence", ["sequence"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  crmUtmCampaigns: defineTable({
    name: v.string(),
    code: v.string(),
    campaignTypeId: v.id("crmCampaignTypes"),
    startDate: v.optional(v.number()),
    endDate: v.optional(v.number()),
    description: v.optional(v.string()),
    color: v.string(),
    icon: v.string(),
    sequence: v.number(),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("sequence", ["sequence"])
    .index("campaignTypeId", ["campaignTypeId"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  crmUtmMediums: defineTable({
    name: v.string(),
    code: v.string(),
    description: v.optional(v.string()),
    color: v.string(),
    icon: v.string(),
    sequence: v.number(),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("sequence", ["sequence"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  crmUtmSources: defineTable({
    name: v.string(),
    code: v.string(),
    description: v.optional(v.string()),
    color: v.string(),
    icon: v.string(),
    sequence: v.number(),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("sequence", ["sequence"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  leadActivity: defineTable({
    leadId: v.id("leadMaster"),
    action: v.string(),
    description: v.string(),
    userId: v.id("users"),
    metadata: v.optional(v.string()),
    createdAt: v.number(),
  })
    .index("leadId", ["leadId"])
    .index("leadId_createdAt", ["leadId", "createdAt"])
    .index("userId", ["userId"]),
  leadApprovalDecisions: defineTable({
    approvalId: v.id("leadApprovals"),
    userId: v.id("users"),
    status: v.union(v.literal("approved"), v.literal("rejected"), v.literal("returned")),
    comment: v.optional(v.string()),
    decidedAt: v.number(),
    createdAt: v.number(),
  })
    .index("approvalId", ["approvalId"])
    .index("userId", ["userId"])
    .index("by_status", ["status"])
    .index("by_created", ["createdAt"]),
  leadApprovals: defineTable({
    leadId: v.id("leadMaster"),
    title: v.string(),
    type: v.union(v.literal("discount"), v.literal("waiver"), v.literal("scholarship"), v.literal("admission"), v.literal("special_pricing"), v.literal("manual")),
    amount: v.number(),
    reason: v.string(),
    approverIds: v.array(v.id("users")),
    mode: v.union(v.literal("any_one"), v.literal("all_required"), v.literal("sequential"), v.literal("parallel")),
    status: v.union(v.literal("pending"), v.literal("approved"), v.literal("rejected"), v.literal("returned")),
    currentApproverIndex: v.number(),
    requestedBy: v.id("users"),
    fallbackApproverId: v.optional(v.id("users")),
    deadline: v.optional(v.number()),
    priority: v.union(v.literal("low"), v.literal("medium"), v.literal("high"), v.literal("critical")),
    discountId: v.optional(v.id("leadDiscounts")),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("leadId", ["leadId"])
    .index("status", ["status"])
    .index("approverIds", ["approverIds"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  leadAssignments: defineTable({
    leadId: v.id("leadMaster"),
    fromUserId: v.optional(v.id("users")),
    toUserId: v.id("users"),
    assignedBy: v.id("users"),
    note: v.optional(v.string()),
    createdAt: v.number(),
  })
    .index("leadId", ["leadId"])
    .index("toUserId", ["toUserId"])
    .index("by_created", ["createdAt"]),
  leadAttachments: defineTable({
    leadId: v.id("leadMaster"),
    fileName: v.string(),
    fileUrl: v.string(),
    fileSize: v.optional(v.number()),
    uploadedBy: v.id("users"),
    createdAt: v.number(),
  })
    .index("leadId", ["leadId"])
    .index("by_created", ["createdAt"]),
  leadCommunications: defineTable({
    leadId: v.id("leadMaster"),
    type: v.union(
      v.literal("Call"), v.literal("WhatsApp"),
      v.literal("Email"), v.literal("SMS"),
    ),
    direction: v.union(v.literal("Inbound"), v.literal("Outbound")),
    subject: v.optional(v.string()),
    message: v.optional(v.string()),
    duration: v.optional(v.number()),
    status: v.optional(v.string()),
    metadata: v.optional(v.string()),
    createdBy: v.id("users"),
    createdAt: v.number(),
  })
    .index("leadId", ["leadId"])
    .index("leadId_type", ["leadId", "type"])
    .index("by_status", ["status"])
    .index("by_created", ["createdAt"]),
  leadConversionPipeline: defineTable({
    leadId: v.id("leadMaster"),
    pipelineType: v.union(v.literal("trial"), v.literal("direct_conversion"), v.literal("installment")),
    trialStartDate: v.optional(v.number()),
    trialEndDate: v.optional(v.number()),
    trialPhase: v.optional(v.union(v.literal("not_started"), v.literal("in_progress"), v.literal("extended"), v.literal("completed"), v.literal("cancelled"))),
    conversionDate: v.optional(v.number()),
    convertedBy: v.optional(v.id("users")),
    revenueAmount: v.optional(v.number()),
    revenueCollected: v.optional(v.number()),
    conversionNotes: v.optional(v.string()),
    paymentPlan: v.optional(v.string()),
    installmentCount: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("leadId", ["leadId"])
    .index("pipelineType", ["pipelineType"])
    .index("trialPhase", ["trialPhase"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  leadCourses: defineTable({
    leadId: v.id("leadMaster"),
    courseId: v.id("courses"),
    addedBy: v.id("users"),
    createdAt: v.number(),
  })
    .index("leadId", ["leadId"])
    .index("courseId", ["courseId"])
    .index("leadId_courseId", ["leadId", "courseId"])
    .index("by_created", ["createdAt"]),
  leadDiscounts: defineTable({
    leadId: v.id("leadMaster"),
    category: v.union(v.literal("scholarship"), v.literal("discount"), v.literal("waiver"), v.literal("adjustment")),
    reason: v.string(),
    amount: v.number(),
    percentage: v.optional(v.number()),
    standardAmount: v.optional(v.number()),
    previousAmount: v.optional(v.number()),
    newAmount: v.optional(v.number()),
    status: v.union(v.literal("draft"), v.literal("pending"), v.literal("approved"), v.literal("rejected"), v.literal("cancelled")),
    approvalRequestId: v.optional(v.id("approvalRequests")),
    requestedBy: v.id("users"),
    approvedBy: v.optional(v.id("users")),
    approvedAt: v.optional(v.number()),
    remarks: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("leadId", ["leadId"])
    .index("status", ["status"])
    .index("leadId_status", ["leadId", "status"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  leadDocuments: defineTable({
    leadId: v.id("leadMaster"),
    name: v.string(),
    url: v.string(),
    type: v.optional(v.string()),
    size: v.optional(v.number()),
    uploadedBy: v.id("users"),
    createdAt: v.number(),
  })
    .index("leadId", ["leadId"])
    .index("by_created", ["createdAt"]),
  leadFollowUpRules: defineTable({
    name: v.string(),
    description: v.optional(v.string()),
    leadStage: v.optional(v.string()),
    leadStatus: v.optional(v.string()),
    daysAfterCreation: v.optional(v.number()),
    daysAfterLastActivity: v.optional(v.number()),
    daysAfterNextAction: v.optional(v.number()),
    actionTemplate: v.string(),
    priority: v.union(v.literal("low"), v.literal("medium"), v.literal("high"), v.literal("critical")),
    assignedTo: v.union(v.literal("owner"), v.literal("manager"), v.literal("team"), v.literal("round_robin")),
    createTask: v.boolean(),
    sendNotification: v.boolean(),
    isActive: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("isActive", ["isActive"])
    .index("leadStage", ["leadStage"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  leadHealthScores: defineTable({
    leadId: v.id("leadMaster"),
    score: v.number(),
    maxScore: v.number(),
    dimensions: v.string(),
    tier: v.string(),
    calculatedAt: v.number(),
    createdAt: v.number(),
  })
    .index("leadId", ["leadId"])
    .index("tier", ["tier"])
    .index("leadId_calculatedAt", ["leadId", "calculatedAt"])
    .index("by_created", ["createdAt"]),
  leadMaster: defineTable({
    firstName: v.string(),
    lastName: v.string(),
    phone: v.string(),
    email: v.optional(v.string()),
    dob: v.optional(v.number()),
    gender: v.optional(v.string()),
    location: v.optional(v.string()),
    verticalId: v.optional(v.id("verticals")),
    subVerticalId: v.optional(v.id("subVerticals")),
    boardId: v.optional(v.id("boards")),
    courseInterest: v.optional(v.string()),
    branchInterestId: v.optional(v.id("branches")),
    academicDetails: v.optional(v.string()),
    stage: v.string(),
    ownerId: v.optional(v.id("users")),
    priority: v.union(v.literal("low"), v.literal("medium"), v.literal("high"), v.literal("critical")),
    probability: v.optional(v.number()),
    expectedRevenue: v.optional(v.number()),
    expectedJoining: v.optional(v.number()),
    nextAction: v.optional(v.string()),
    nextActionDate: v.optional(v.number()),
    standardAmount: v.optional(v.number()),
    discountAmount: v.optional(v.number()),
    waiverAmount: v.optional(v.number()),
    finalPayable: v.optional(v.number()),
    source: v.optional(v.string()),
    campaign: v.optional(v.string()),
    utm: v.optional(v.string()),
    channel: v.optional(v.string()),
    whatsappUsername: v.optional(v.string()),
    whatsappPin: v.optional(v.string()),
    referralId: v.optional(v.id("users")),
    status: v.union(v.literal("active"), v.literal("converted"), v.literal("lost"), v.literal("archived")),
    tags: v.optional(v.array(v.string())),
    createdBy: v.id("users"),
    parentLeadId: v.optional(v.id("leadMaster")),
    duplicateOf: v.optional(v.id("leadMaster")),
    mergeCandidate: v.optional(v.id("leadMaster")),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("stage", ["stage"])
    .index("ownerId", ["ownerId"])
    .index("priority", ["priority"])
    .index("status", ["status"])
    .index("verticalId", ["verticalId"])
    .index("branchInterestId", ["branchInterestId"])
    .index("ownerId_stage", ["ownerId", "stage"])
    .index("nextActionDate", ["nextActionDate"])
    .index("createdAt", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  leadMeetings: defineTable({
    leadId: v.id("leadMaster"),
    meetingType: v.string(),
    meetingDate: v.number(),
    duration: v.optional(v.number()),
    location: v.optional(v.string()),
    meetingLink: v.optional(v.string()),
    attendees: v.optional(v.array(v.id("users"))),
    status: v.union(
      v.literal("scheduled"), v.literal("completed"),
      v.literal("cancelled"), v.literal("rescheduled"),
    ),
    notes: v.optional(v.string()),
    createdBy: v.id("users"),
    createdAt: v.number(),
    updatedAt: v.optional(v.number()),
  })
    .index("leadId", ["leadId"])
    .index("leadId_meetingDate", ["leadId", "meetingDate"])
    .index("status", ["status"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  leadNotes: defineTable({
    leadId: v.id("leadMaster"),
    content: v.string(),
    createdBy: v.id("users"),
    type: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.optional(v.number()),
  })
    .index("leadId", ["leadId"])
    .index("leadId_createdAt", ["leadId", "createdAt"])
    .index("by_updated", ["updatedAt"]),
  leadPayments: defineTable({
    leadId: v.id("leadMaster"),
    amount: v.number(),
    mode: v.union(v.literal("cash"), v.literal("upi"), v.literal("bank"), v.literal("card"), v.literal("cheque"), v.literal("online")),
    reference: v.optional(v.string()),
    receiptUrl: v.optional(v.string()),
    enteredBy: v.id("users"),
    verifiedBy: v.optional(v.id("users")),
    verifiedAt: v.optional(v.number()),
    status: v.union(v.literal("pending"), v.literal("verified"), v.literal("rejected")),
    rejectionReason: v.optional(v.string()),
    notes: v.optional(v.string()),
    verificationRequestId: v.optional(v.id("verification_requests")),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("leadId", ["leadId"])
    .index("status", ["status"])
    .index("leadId_status", ["leadId", "status"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  leadStageHistory: defineTable({
    leadId: v.id("leadMaster"),
    fromStage: v.optional(v.string()),
    toStage: v.string(),
    changedBy: v.id("users"),
    note: v.optional(v.string()),
    createdAt: v.number(),
  })
    .index("leadId", ["leadId"])
    .index("leadId_createdAt", ["leadId", "createdAt"]),
  leadStatusEngine: defineTable({
    fromStatus: v.string(),
    toStatus: v.string(),
    allowed: v.boolean(),
    requiresPayment: v.boolean(),
    requiresApproval: v.boolean(),
    irreversible: v.boolean(),
    triggerWorkflowId: v.optional(v.id("workflows")),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("fromStatus_toStatus", ["fromStatus", "toStatus"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  leadTasks: defineTable({
    leadId: v.id("leadMaster"),
    title: v.string(),
    description: v.optional(v.string()),
    ownerId: v.id("users"),
    assignedTo: v.optional(v.id("users")),
    dueDate: v.optional(v.number()),
    status: v.union(v.literal("pending"), v.literal("in_progress"), v.literal("completed"), v.literal("cancelled")),
    priority: v.union(v.literal("low"), v.literal("medium"), v.literal("high"), v.literal("critical")),
    isApproved: v.optional(v.boolean()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("leadId", ["leadId"])
    .index("ownerId", ["ownerId"])
    .index("assignedTo", ["assignedTo"])
    .index("status", ["status"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  leadTimeline: defineTable({
    leadId: v.id("leadMaster"),
    organizationId: v.optional(v.id("organization")),
    companyId: v.optional(v.id("companies")),
    branchId: v.optional(v.id("branches")),
    eventType: v.string(),
    title: v.string(),
    description: v.optional(v.string()),
    metadata: v.optional(v.string()),
    performedBy: v.optional(v.id("users")),
    performedAt: v.number(),
    createdAt: v.number(),
  })
    .index("leadId", ["leadId"])
    .index("leadId_performedAt", ["leadId", "performedAt"])
    .index("eventType", ["eventType"])
    .index("by_org", ["organizationId"])
    .index("by_company", ["companyId"])
    .index("by_branch", ["branchId"])
    .index("by_created", ["createdAt"]),
  leadWhatsAppMessages: defineTable({
    leadId: v.id("leadMaster"),
    templateName: v.optional(v.string()),
    message: v.string(),
    whatsappUrl: v.string(),
    sentBy: v.id("users"),
    status: v.union(v.literal("sent"), v.literal("opened"), v.literal("clicked"), v.literal("replied"), v.literal("failed")),
    template: v.optional(v.union(
      v.literal("greeting"), v.literal("followup"), v.literal("reminder"),
      v.literal("offer"), v.literal("approval"), v.literal("conversion"), v.literal("manual")
    )),
    createdAt: v.number(),
  })
    .index("leadId", ["leadId"])
    .index("leadId_createdAt", ["leadId", "createdAt"])
    .index("by_status", ["status"]),
  opportunities: defineTable({
    leadId: v.id("leadMaster"),
    ownerId: v.id("users"),
    title: v.string(),
    stageId: v.id("salesOpportunityStages"),
    probability: v.number(),
    expectedRevenue: v.optional(v.number()),
    actualRevenue: v.optional(v.number()),
    currency: v.optional(v.string()),
    expectedCloseDate: v.optional(v.number()),
    actualCloseDate: v.optional(v.number()),
    notes: v.optional(v.string()),
    tags: v.optional(v.array(v.string())),
    lostReasonId: v.optional(v.id("crmLostReasons")),
    competitiveInfo: v.optional(v.string()),
    isActive: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("leadId", ["leadId"])
    .index("ownerId", ["ownerId"])
    .index("stageId", ["stageId"])
    .index("by_active", ["isActive"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  opportunityStageHistory: defineTable({
    opportunityId: v.id("opportunities"),
    fromStageId: v.optional(v.id("salesOpportunityStages")),
    toStageId: v.id("salesOpportunityStages"),
    changedBy: v.id("users"),
    note: v.optional(v.string()),
    createdAt: v.number(),
  })
    .index("opportunityId", ["opportunityId"])
    .index("opportunityId_createdAt", ["opportunityId", "createdAt"]),
  quotationLineItems: defineTable({
    quotationId: v.id("quotations"),
    description: v.string(),
    quantity: v.number(),
    unitPrice: v.number(),
    discountPercent: v.optional(v.number()),
    discountAmount: v.optional(v.number()),
    taxPercent: v.optional(v.number()),
    taxAmount: v.optional(v.number()),
    total: v.number(),
    sortOrder: v.number(),
    createdAt: v.number(),
  })
    .index("quotationId", ["quotationId"])
    .index("by_created", ["createdAt"]),
  quotationVersions: defineTable({
    quotationId: v.id("quotations"),
    version: v.number(),
    data: v.string(),
    changedBy: v.id("users"),
    changeNotes: v.optional(v.string()),
    createdAt: v.number(),
  })
    .index("quotationId", ["quotationId"])
    .index("quotationId_version", ["quotationId", "version"])
    .index("by_created", ["createdAt"]),
  quotations: defineTable({
    opportunityId: v.id("opportunities"),
    leadId: v.id("leadMaster"),
    quoteNumber: v.string(),
    status: v.union(v.literal("draft"), v.literal("sent"), v.literal("accepted"), v.literal("rejected"), v.literal("expired"), v.literal("revised")),
    issuedDate: v.number(),
    expiryDate: v.optional(v.number()),
    subtotal: v.number(),
    discountPercent: v.optional(v.number()),
    discountAmount: v.optional(v.number()),
    gstPercent: v.optional(v.number()),
    gstAmount: v.optional(v.number()),
    total: v.number(),
    currency: v.optional(v.string()),
    notes: v.optional(v.string()),
    terms: v.optional(v.string()),
    validUntil: v.optional(v.number()),
    createdBy: v.id("users"),
    approvedBy: v.optional(v.id("users")),
    pdfUrl: v.optional(v.string()),
    isActive: v.boolean(),
    version: v.number(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("opportunityId", ["opportunityId"])
    .index("leadId", ["leadId"])
    .index("status", ["status"])
    .index("by_active", ["isActive"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  salesInvoiceTypes: defineTable({
    name: v.string(),
    code: v.string(),
    invoiceCategory: v.optional(v.string()),
    sequence: v.number(),
    color: v.string(),
    icon: v.string(),
    description: v.optional(v.string()),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("sequence", ["sequence"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  salesOpportunityStages: defineTable({
    name: v.string(),
    code: v.string(),
    stageOrder: v.number(),
    probability: v.number(),
    isClosed: v.boolean(),
    description: v.optional(v.string()),
    color: v.string(),
    icon: v.string(),
    sequence: v.number(),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("sequence", ["sequence"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  salesOpportunityTypes: defineTable({
    name: v.string(),
    code: v.string(),
    opportunityCategory: v.optional(v.string()),
    sequence: v.number(),
    color: v.string(),
    icon: v.string(),
    description: v.optional(v.string()),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("sequence", ["sequence"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  salesPaymentStatuses: defineTable({
    name: v.string(),
    code: v.string(),
    statusCategory: v.optional(v.string()),
    sequence: v.number(),
    color: v.string(),
    icon: v.string(),
    description: v.optional(v.string()),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("sequence", ["sequence"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  salesQuotationStatuses: defineTable({
    name: v.string(),
    code: v.string(),
    statusCategory: v.optional(v.string()),
    sequence: v.number(),
    color: v.string(),
    icon: v.string(),
    description: v.optional(v.string()),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("sequence", ["sequence"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  salesTaxSlabs: defineTable({
    name: v.string(),
    code: v.string(),
    slabType: v.optional(v.string()),
    fromAmount: v.optional(v.number()),
    toAmount: v.optional(v.number()),
    taxRate: v.number(),
    sequence: v.number(),
    color: v.string(),
    icon: v.string(),
    description: v.optional(v.string()),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("sequence", ["sequence"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  salesTerritories: defineTable({
    name: v.string(),
    code: v.string(),
    territoryType: v.optional(v.string()),
    sequence: v.number(),
    color: v.string(),
    icon: v.string(),
    description: v.optional(v.string()),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("sequence", ["sequence"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  // ─── Collection Engine Tables (PATCH-EEOS Collection) ────────────

  payment_plans: defineTable({
    leadId: v.id("leadMaster"),
    totalAmount: v.number(),
    installmentCount: v.number(),
    installmentAmount: v.number(),
    frequency: v.union(v.literal("weekly"), v.literal("monthly"), v.literal("quarterly"), v.literal("custom")),
    startDate: v.number(),
    graceDays: v.number(),
    status: v.union(v.literal("active"), v.literal("cancelled")),
    createdBy: v.id("users"),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("leadId", ["leadId"])
    .index("status", ["status"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),

  payment_installments: defineTable({
    planId: v.id("payment_plans"),
    leadId: v.id("leadMaster"),
    installmentNumber: v.number(),
    amount: v.number(),
    dueDate: v.number(),
    status: v.union(v.literal("planned"), v.literal("due"), v.literal("paid"), v.literal("overdue"), v.literal("cancelled")),
    paidAt: v.optional(v.number()),
    paymentId: v.optional(v.id("leadPayments")),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("leadId", ["leadId"])
    .index("planId", ["planId"])
    .index("dueDate", ["dueDate"])
    .index("status", ["status"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),

  payment_pdcs: defineTable({
    leadId: v.id("leadMaster"),
    chequeNumber: v.string(),
    bank: v.string(),
    chequeDate: v.number(),
    amount: v.number(),
    attachment: v.optional(v.string()),
    status: v.union(v.literal("scheduled"), v.literal("deposited"), v.literal("cleared"), v.literal("bounced"), v.literal("cancelled")),
    depositDate: v.optional(v.number()),
    depositedBy: v.optional(v.id("users")),
    bouncedAt: v.optional(v.number()),
    bounceReason: v.optional(v.string()),
    linkedPaymentId: v.optional(v.id("leadPayments")),
    createdBy: v.id("users"),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("leadId", ["leadId"])
    .index("status", ["status"])
    .index("chequeDate", ["chequeDate"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),

  payment_commitments: defineTable({
    leadId: v.id("leadMaster"),
    amount: v.number(),
    commitDate: v.number(),
    reason: v.optional(v.string()),
    confidence: v.union(v.literal("low"), v.literal("medium"), v.literal("high")),
    ownerId: v.id("users"),
    status: v.union(v.literal("active"), v.literal("completed"), v.literal("expired"), v.literal("cancelled")),
    paymentId: v.optional(v.id("leadPayments")),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("leadId", ["leadId"])
    .index("status", ["status"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
};