import { defineTable } from "convex/server";
import { v } from "convex/values";

export const organizationTables = {
  boards: defineTable({
    name: v.string(),
    code: v.string(),
    subVerticalId: v.optional(v.id("subVerticals")),
    verticalId: v.optional(v.id("verticals")),
    description: v.optional(v.string()),
    status: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("code", ["code"])
    .index("subVerticalId", ["subVerticalId"])
    .index("by_status", ["status"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  branches: defineTable({
    name: v.string(),
    code: v.string(),
    parentType: v.optional(v.union(v.literal("group"), v.literal("company"))),
    parentId: v.optional(v.string()),
    organizationId: v.optional(v.id("organizations")),
    email: v.optional(v.string()),
    phone: v.optional(v.string()),
    address: v.optional(v.string()),
    isActive: v.optional(v.boolean()),
    description: v.optional(v.string()),
    color: v.optional(v.string()),
    icon: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_code", ["code"])
    .index("by_organization", ["organizationId"])
    .index("parentType_parentId", ["parentType", "parentId"])
    .index("by_active", ["isActive"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  companies: defineTable({
    name: v.string(),
    code: v.string(),
    companyType: v.optional(v.string()),
    status: v.optional(v.string()),
    parentType: v.optional(v.union(v.literal("group"))),
    parentId: v.optional(v.string()),
    departmentId: v.optional(v.id("departments")),
    description: v.optional(v.string()),
    color: v.optional(v.string()),
    icon: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("code", ["code"])
    .index("departmentId", ["departmentId"])
    .index("by_status", ["status"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  departments: defineTable({
    name: v.string(),
    code: v.string(),
    parentType: v.optional(v.union(v.literal("group"), v.literal("company"))),
    parentId: v.optional(v.string()),
    branchId: v.optional(v.id("branches")),
    managerId: v.optional(v.id("users")),
    isActive: v.optional(v.boolean()),
    description: v.optional(v.string()),
    color: v.optional(v.string()),
    icon: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_code", ["code"])
    .index("by_branch", ["branchId"])
    .index("parentType_parentId", ["parentType", "parentId"])
    .index("by_active", ["isActive"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  designations: defineTable({
    name: v.string(),
    code: v.string(),
    reportsTo: v.optional(v.id("designations")),
    status: v.string(),
    description: v.optional(v.string()),
    color: v.optional(v.string()),
    icon: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("code", ["code"])
    .index("by_status", ["status"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  orgBranches: defineTable({
    name: v.string(),
    code: v.string(),
    color: v.string(),
    icon: v.string(),
    city: v.string(),
    state: v.string(),
    country: v.string(),
    address: v.optional(v.string()),
    phone: v.optional(v.string()),
    email: v.optional(v.string()),
    managerName: v.optional(v.string()),
    displayOrder: v.number(),
    isActive: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("displayOrder", ["displayOrder"])
    .index("by_active", ["isActive"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  orgCompanies: defineTable({
    name: v.string(),
    code: v.string(),
    color: v.string(),
    icon: v.string(),
    legalName: v.optional(v.string()),
    registrationNumber: v.optional(v.string()),
    taxNumber: v.optional(v.string()),
    email: v.optional(v.string()),
    phone: v.optional(v.string()),
    website: v.optional(v.string()),
    address: v.optional(v.string()),
    city: v.string(),
    state: v.string(),
    country: v.string(),
    logoUrl: v.optional(v.string()),
    description: v.optional(v.string()),
    displayOrder: v.number(),
    isActive: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("displayOrder", ["displayOrder"])
    .index("by_active", ["isActive"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  orgDepartments: defineTable({
    name: v.string(),
    code: v.string(),
    description: v.optional(v.string()),
    color: v.string(),
    icon: v.string(),
    sequence: v.number(),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("sequence", ["sequence"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  orgDesignations: defineTable({
    name: v.string(),
    code: v.string(),
    description: v.optional(v.string()),
    color: v.string(),
    icon: v.string(),
    sequence: v.number(),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("sequence", ["sequence"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  orgTeams: defineTable({
    name: v.string(),
    code: v.string(),
    description: v.optional(v.string()),
    color: v.string(),
    icon: v.string(),
    sequence: v.number(),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("sequence", ["sequence"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  organizations: defineTable({
    name: v.string(),
    code: v.string(),
    description: v.optional(v.string()),
    email: v.optional(v.string()),
    phone: v.optional(v.string()),
    address: v.optional(v.string()),
    taxId: v.optional(v.string()),
    isActive: v.optional(v.boolean()),
    color: v.optional(v.string()),
    icon: v.optional(v.string()),
    createdAt: v.optional(v.number()),
    updatedAt: v.optional(v.number()),
  })
    .index("by_code", ["code"])
    .index("by_active", ["isActive"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  subVerticals: defineTable({
    name: v.string(),
    code: v.string(),
    verticalId: v.id("verticals"),
    description: v.optional(v.string()),
    status: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("code", ["code"])
    .index("verticalId", ["verticalId"])
    .index("by_status", ["status"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  teams: defineTable({
    name: v.string(),
    code: v.string(),
    departmentId: v.id("departments"),
    description: v.optional(v.string()),
    leadId: v.optional(v.id("users")),
    leadUserId: v.optional(v.id("users")),
    isActive: v.optional(v.boolean()),
    color: v.optional(v.string()),
    icon: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_code", ["code"])
    .index("by_department", ["departmentId"])
    .index("by_lead", ["leadId"])
    .index("by_active", ["isActive"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
  verticals: defineTable({
    name: v.string(),
    code: v.string(),
    description: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("code", ["code"])
    .index("by_created", ["createdAt"])
    .index("by_updated", ["updatedAt"]),
};