/**
 * Enterprise Adoption Helpers
 *
 * Standardized helper functions for wrapping existing Convex mutation handlers
 * with enterprise integration (ScopeEngine + Event Pipeline + Timeline + Audit).
 *
 * Usage:
 *   // Before:
 *   export const createFoo = mutation({
 *     args: { ... },
 *     handler: async (ctx, args) => { ... },
 *   });
 *
 *   // After:
 *   export const createFoo = adoptMutation("finance", "foo", "create")({
 *     args: { ..., createdBy: v.id("users") },
 *     handler: async (ctx, args) => { ... },
 *   });
 *
 * This reduces boilerplate and ensures every module is enterprise-integrated.
 */

import { v } from "convex/values";
import { mutation, MutationCtx } from "./_generated/server";
import { Id } from "./_generated/dataModel";
import { withScopeAndEvents, ScopeAndEventsConfig } from "./withScopeAndEvents";
import { Events } from "./eventRegistry";

// ─── Standard Scope Keys for common args ───────────────────

type WithScope = {
  createdBy?: Id<"users">;
  performedBy?: Id<"users">;
  userId?: Id<"users">;
  companyId?: Id<"companies">;
  branchId?: Id<"branches">;
  departmentId?: Id<"departments">;
};

type MutationHandler<P> = (ctx: MutationCtx, args: P) => Promise<any>;

// ─── Adoption Factory ──────────────────────────────────────

interface AdoptionConfig {
  module: string;
  entity: string;
  operation: "create" | "update" | "delete" | "approve";
  eventType?: string;
  title?: string;
  notifyViaMatrix?: boolean;
  autoGenerateDocs?: ScopeAndEventsConfig["autoGenerateDocs"];
}

/**
 * adoptMutation — wraps a mutation handler with enterprise integration
 *
 * Automatically extracts:
 *   - userId from createdBy / performedBy / userId fields
 *   - companyId, branchId from args
 *
 * Example:
 *   export const createStudent = adoptMutation("admission", "student", "create", {
 *     eventType: Events.ADMISSION.STUDENT_CREATED,
 *     notifyViaMatrix: true,
 *   })({
 *     args: { firstName: v.string(), ... },
 *     handler: async (ctx, args) => { ... },
 *   });
 */
export function adoptMutation<P extends WithScope & Record<string, any>>(
  module: string,
  entity: string,
  operation: "create" | "update" | "delete" | "approve",
  extraConfig?: {
    eventType?: string;
    title?: string;
    notifyViaMatrix?: boolean;
    autoGenerateDocs?: ScopeAndEventsConfig["autoGenerateDocs"];
  },
) {
  // Build standard config
  const config: ScopeAndEventsConfig<P, any> = {
    operation,
    module,
    entity,
    eventType: extraConfig?.eventType || `${module}.${entity}.${operation}`,
    title: extraConfig?.title || `${module}.${entity}.${operation}`,
    getUserId: (args: P) => args.createdBy || args.performedBy || args.userId,
    getEntityCompanyId: (args: P) => args.companyId as string | undefined,
    getEntityBranchId: (args: P) => args.branchId as string | undefined,
    notifyViaMatrix: extraConfig?.notifyViaMatrix ?? false,
    autoGenerateDocs: extraConfig?.autoGenerateDocs,
  };

  return function <A extends Record<string, any>, R>(
    mutationDef: { args: A; handler: (ctx: MutationCtx, args: P) => Promise<R> },
  ) {
    return mutation({
      args: mutationDef.args,
      handler: withScopeAndEvents(config, mutationDef.handler as any) as any,
    });
  };
}

// ─── Pre-built Configurations for Common Entity Types ──────

export const createStudentConfig = {
  module: "admission" as const,
  entity: "student" as const,
  operation: "create" as const,
  eventType: Events.ADMISSION.STUDENT_CREATED,
  title: "Student Created",
  notifyViaMatrix: true,
};

export const updateStudentConfig = {
  module: "admission" as const,
  entity: "student" as const,
  operation: "update" as const,
  eventType: Events.ADMISSION.STUDENT_UPDATED,
  title: "Student Updated",
};

export const archiveStudentConfig = {
  module: "admission" as const,
  entity: "student" as const,
  operation: "delete" as const,
  eventType: Events.ADMISSION.STUDENT_CANCELLED,
  title: "Student Archived",
  notifyViaMatrix: true,
};

export const createFeeConfig = {
  module: "finance" as const,
  entity: "fee_structure" as const,
  operation: "create" as const,
  eventType: Events.FINANCE.FEE_STRUCTURE_CREATED,
  title: "Fee Structure Created",
};

export const createPaymentConfig = {
  module: "finance" as const,
  entity: "payment" as const,
  operation: "create" as const,
  eventType: Events.FINANCE.PAYMENT_RECEIVED,
  title: "Payment Received",
  notifyViaMatrix: true,
};

export const createRefundConfig = {
  module: "finance" as const,
  entity: "refund" as const,
  operation: "create" as const,
  eventType: Events.FINANCE.REFUND_INITIATED,
  title: "Refund Initiated",
  notifyViaMatrix: true,
};

export const approveRefundConfig = {
  module: "finance" as const,
  entity: "refund" as const,
  operation: "approve" as const,
  eventType: Events.FINANCE.REFUND_APPROVED,
  title: "Refund Approved",
  notifyViaMatrix: true,
};

export const createChequeConfig = {
  module: "finance" as const,
  entity: "pdc" as const,
  operation: "create" as const,
  eventType: Events.FINANCE.CHEQUE_RECEIVED,
  title: "PDC Created",
  notifyViaMatrix: true,
};

export const createEmployeeConfig = {
  module: "hr" as const,
  entity: "employee" as const,
  operation: "create" as const,
  eventType: Events.HR.EMPLOYEE_JOINED,
  title: "Employee Joined",
  notifyViaMatrix: true,
};

export const createLeadConfig = {
  module: "crm" as const,
  entity: "lead" as const,
  operation: "create" as const,
  eventType: Events.CRM.LEAD_CREATED,
  title: "Lead Created",
  notifyViaMatrix: true,
};

export const convertLeadConfig = {
  module: "crm" as const,
  entity: "lead" as const,
  operation: "update" as const,
  eventType: Events.CRM.LEAD_CONVERTED,
  title: "Lead Converted",
  notifyViaMatrix: true,
};

export const createTicketeConfig = {
  module: "support" as const,
  entity: "ticket" as const,
  operation: "create" as const,
  eventType: Events.SUPPORT.TICKET_CREATED,
  title: "Ticket Created",
  notifyViaMatrix: true,
};

export const approveLeaveConfig = {
  module: "hr" as const,
  entity: "leave" as const,
  operation: "approve" as const,
  eventType: Events.HR.LEAVE_APPROVED,
  title: "Leave Approved",
  notifyViaMatrix: true,
};

export const markAttendanceConfig = {
  module: "hr" as const,
  entity: "attendance" as const,
  operation: "create" as const,
  eventType: Events.HR.ATTENDANCE_MARKED,
  title: "Attendance Marked",
};

export const createCampaignConfig = {
  module: "marketing" as const,
  entity: "campaign" as const,
  operation: "create" as const,
  eventType: Events.MARKETING.CAMPAIGN_CREATED,
  title: "Campaign Created",
};

export const createStockConfig = {
  module: "inventory" as const,
  entity: "stock" as const,
  operation: "create" as const,
  eventType: Events.INVENTORY.STOCK_ADDED,
  title: "Stock Added",
  notifyViaMatrix: true,
};

export const scheduleClassConfig = {
  module: "academic" as const,
  entity: "class" as const,
  operation: "create" as const,
  eventType: Events.ACADEMIC.CLASS_SCHEDULED,
  title: "Class Scheduled",
  notifyViaMatrix: true,
};

export const publishExamConfig = {
  module: "exam" as const,
  entity: "exam" as const,
  operation: "update" as const,
  eventType: Events.EXAM.PUBLISHED,
  title: "Exam Published",
  notifyViaMatrix: true,
};

export const closeTicketConfig = {
  module: "support" as const,
  entity: "ticket" as const,
  operation: "update" as const,
  eventType: Events.SUPPORT.TICKET_CLOSED,
  title: "Ticket Closed",
  notifyViaMatrix: true,
};
