/**
 * Employee Engine — Enterprise-integrated Employee CRUD
 *
 * Every mutation uses withScopeAndEvents() for:
 *   - ScopeEngine authorization (company/branch/department scope)
 *   - Event Pipeline (hr.employee.joined, hr.employee.updated, etc.)
 *   - Timeline auto-recording (replaces manual createTimelineEvent)
 *   - Audit auto-logging
 *   - Notification Matrix (hr, manager, it, department_head notified)
 *   - Auto-document generation (offer_letter, appointment_letter)
 */

import { v } from "convex/values";
import { paginationOptsValidator } from "convex/server";
import { mutation, query, internalMutation } from "./_generated/server";
import { Doc, Id } from "./_generated/dataModel";
import { paginatedQuery, batchGet, type PaginatedResponse } from "./queryHelpers";
import { withScopeAndEvents } from "./withScopeAndEvents";
import { Events } from "./eventRegistry";

// ─── Helpers ─────────────────────────────────────────────────────

async function generateEmployeeCode(ctx: { db: { query: (table: string) => any } }): Promise<string> {
  const employees = await ctx.db.query("employeeMaster").collect();
  const count = employees.length + 1;
  return `EMP-${String(count).padStart(5, "0")}`;
}

// ─── Create Employee (Enterprise-Integrated) ─────────────────────

export const createEmployee = mutation({
  args: {
    firstName: v.string(),
    lastName: v.string(),
    middleName: v.optional(v.string()),
    displayName: v.optional(v.string()),
    gender: v.optional(v.string()),
    dateOfBirth: v.optional(v.number()),
    nationality: v.optional(v.string()),
    mobile: v.string(),
    email: v.optional(v.string()),
    countryCode: v.optional(v.string()),
    employmentType: v.union(
      v.literal("permanent"), v.literal("contract"),
      v.literal("part_time"), v.literal("intern"),
      v.literal("freelancer"), v.literal("consultant"),
    ),
    primaryRole: v.union(
      v.literal("super_admin"), v.literal("ceo"), v.literal("coo"),
      v.literal("cto"), v.literal("department_head"),
      v.literal("manager"), v.literal("employee"),
    ),
    joiningDate: v.optional(v.number()),
    probationEndDate: v.optional(v.number()),
    companyId: v.optional(v.id("companies")),
    branchId: v.optional(v.id("branches")),
    departmentId: v.optional(v.id("departments")),
    designationId: v.optional(v.id("designations")),
    reportingManagerId: v.optional(v.id("employeeMaster")),
    employeeCategoryId: v.optional(v.id("hrEmployeeCategories")),
    workLocation: v.optional(v.string()),
    experienceLevel: v.optional(v.string()),
    createdByUserId: v.optional(v.id("users")),
  },
  handler: withScopeAndEvents(
    {
      operation: "create",
      module: "hr",
      entity: "employee",
      eventType: Events.HR.EMPLOYEE_JOINED,
      title: "Employee Created",
      getUserId: (args) => args.createdByUserId,
      getEntityCompanyId: (args) => args.companyId,
      getEntityBranchId: (args) => args.branchId,
      notifyViaMatrix: true,
      autoGenerateDocs: [
        {
          documentType: "offer_letter",
          contextBuilder: (args, result: any) => ({
            employeeId: result.employeeId,
            employeeName: `${args.firstName} ${args.lastName}`,
            employeeCode: result.employeeCode,
            employmentType: args.employmentType,
            joiningDate: args.joiningDate,
            companyId: args.companyId,
            branchId: args.branchId,
            generatedAt: new Date().toISOString(),
          }),
        },
      ],
    },
    async (ctx, args) => {
      const personId = await ctx.db.insert("personMaster", {
        firstName: args.firstName,
        middleName: args.middleName,
        lastName: args.lastName,
        displayName: args.displayName || `${args.firstName} ${args.lastName}`,
        gender: args.gender,
        dateOfBirth: args.dateOfBirth,
        nationality: args.nationality,
        status: "active",
        createdAt: Date.now(),
        updatedAt: Date.now(),
      });

      await ctx.db.insert("contactMethods", {
        personId,
        type: "Mobile",
        label: "Personal",
        value: args.mobile,
        countryCode: args.countryCode || "91",
        preferred: true,
        verified: false,
        visibility: "organization",
        active: true,
      });

      if (args.email) {
        await ctx.db.insert("contactMethods", {
          personId,
          type: "Email",
          label: "Personal",
          value: args.email,
          preferred: true,
          verified: false,
          visibility: "organization",
          active: true,
        });
      }

      const employeeCode = await generateEmployeeCode(ctx);

      await ctx.db.insert("personProfiles", {
        personId,
        profileType: "employee",
        profileReferenceId: employeeCode,
        active: true,
        primaryProfile: true,
      });

      const employeeId = await ctx.db.insert("employeeMaster", {
        employeeCode,
        personId,
        employmentType: args.employmentType,
        primaryRole: args.primaryRole,
        joiningDate: args.joiningDate,
        probationEndDate: args.probationEndDate,
        companyId: args.companyId,
        branchId: args.branchId,
        departmentId: args.departmentId,
        designationId: args.designationId,
        reportingManagerId: args.reportingManagerId,
        employeeCategoryId: args.employeeCategoryId,
        workLocation: args.workLocation,
        experienceLevel: args.experienceLevel,
        status: "onboarding",
        createdAt: Date.now(),
        updatedAt: Date.now(),
      });

      return { employeeId, personId, employeeCode };
    }
  ),
});

// ─── Get Employee ────────────────────────────────────────────────

export const getEmployee = query({
  args: { employeeId: v.id("employeeMaster") },
  handler: async (ctx, args) => {
    const employee = await ctx.db.get(args.employeeId);
    if (!employee) return null;

    const person = await ctx.db.get(employee.personId);
    const contactMethods = await ctx.db
      .query("contactMethods")
      .withIndex("personId", (q) => q.eq("personId", employee.personId))
      .collect();
    const profiles = await ctx.db
      .query("personProfiles")
      .withIndex("personId", (q) => q.eq("personId", employee.personId))
      .collect();

    const department = employee.departmentId ? await ctx.db.get(employee.departmentId) : null;
    const designation = employee.designationId ? await ctx.db.get(employee.designationId) : null;
    const branch = employee.branchId ? await ctx.db.get(employee.branchId) : null;
    const company = employee.companyId ? await ctx.db.get(employee.companyId) : null;

    let reportingManager: any = null;
    if (employee.reportingManagerId) {
      const mgr = await ctx.db.get(employee.reportingManagerId);
      if (mgr) {
        const mgrPerson = await ctx.db.get(mgr.personId);
        reportingManager = {
          employeeId: mgr._id,
          employeeCode: mgr.employeeCode,
          displayName: mgrPerson?.displayName || "Unknown",
        };
      }
    }

    return {
      ...employee,
      person,
      contactMethods,
      profiles,
      department,
      designation,
      branch,
      company,
      reportingManager,
    };
  },
});

// ─── Update Employee (Enterprise-Integrated) ─────────────────────

export const updateEmployee = mutation({
  args: {
    employeeId: v.id("employeeMaster"),
    companyId: v.optional(v.id("companies")),
    branchId: v.optional(v.id("branches")),
    departmentId: v.optional(v.id("departments")),
    designationId: v.optional(v.id("designations")),
    reportingManagerId: v.optional(v.id("employeeMaster")),
    employmentType: v.optional(v.union(
      v.literal("permanent"), v.literal("contract"),
      v.literal("part_time"), v.literal("intern"),
      v.literal("freelancer"), v.literal("consultant"),
    )),
    primaryRole: v.optional(v.union(
      v.literal("super_admin"), v.literal("ceo"), v.literal("coo"),
      v.literal("cto"), v.literal("department_head"),
      v.literal("manager"), v.literal("employee"),
    )),
    workLocation: v.optional(v.string()),
    experienceLevel: v.optional(v.string()),
    employeeCategoryId: v.optional(v.id("hrEmployeeCategories")),
    changedBy: v.id("users"),
  },
  handler: withScopeAndEvents(
    {
      operation: "update",
      module: "hr",
      entity: "employee",
      eventType: Events.HR.EMPLOYEE_ONBOARDED,
      title: "Employee Updated",
      getUserId: (args) => args.changedBy,
      getEntityCompanyId: (args) => args.companyId,
      getEntityBranchId: (args) => args.branchId,
      notifyViaMatrix: false,
    },
    async (ctx, args) => {
      const { employeeId, changedBy, ...updates } = args;
      const employee = await ctx.db.get(employeeId);
      if (!employee) throw new Error("Employee not found");

      await ctx.db.patch(employeeId, {
        ...updates,
        updatedAt: Date.now(),
      });

      return { success: true };
    }
  ),
});

// ─── Archive Employee (Enterprise-Integrated) ────────────────────

export const archiveEmployee = mutation({
  args: {
    employeeId: v.id("employeeMaster"),
    changedBy: v.id("users"),
    reason: v.optional(v.string()),
  },
  handler: withScopeAndEvents(
    {
      operation: "delete",
      module: "hr",
      entity: "employee",
      eventType: Events.HR.EMPLOYEE_EXITED,
      title: "Employee Archived",
      getUserId: (args) => args.changedBy,
      getEntityCompanyId: () => undefined,
      getEntityBranchId: () => undefined,
      notifyViaMatrix: true,
    },
    async (ctx, args) => {
      const employee = await ctx.db.get(args.employeeId);
      if (!employee) throw new Error("Employee not found");

      await ctx.db.patch(args.employeeId, {
        status: "archived",
        updatedAt: Date.now(),
      });

      return { success: true };
    }
  ),
});

// ─── Restore Employee (Enterprise-Integrated) ────────────────────

export const restoreEmployee = mutation({
  args: {
    employeeId: v.id("employeeMaster"),
    changedBy: v.id("users"),
  },
  handler: withScopeAndEvents(
    {
      operation: "update",
      module: "hr",
      entity: "employee",
      eventType: Events.HR.EMPLOYEE_JOINED,
      title: "Employee Restored",
      getUserId: (args) => args.changedBy,
      getEntityCompanyId: () => undefined,
      getEntityBranchId: () => undefined,
      notifyViaMatrix: false,
    },
    async (ctx, args) => {
      const employee = await ctx.db.get(args.employeeId);
      if (!employee) throw new Error("Employee not found");

      await ctx.db.patch(args.employeeId, {
        status: "active",
        updatedAt: Date.now(),
      });

      return { success: true };
    }
  ),
});

// ─── List Employees (Scope-enforcing query) ──────────────────────

export const listEmployees = query({
  args: {
    paginationOpts: paginationOptsValidator,
    search: v.optional(v.string()),
    status: v.optional(v.union(
      v.literal("active"), v.literal("onboarding"),
      v.literal("probation"), v.literal("suspended"),
      v.literal("resigned"), v.literal("terminated"),
      v.literal("retired"), v.literal("archived"),
    )),
    departmentId: v.optional(v.id("departments")),
    branchId: v.optional(v.id("branches")),
    companyId: v.optional(v.id("companies")),
    designationId: v.optional(v.id("designations")),
    employmentType: v.optional(v.union(
      v.literal("permanent"), v.literal("contract"),
      v.literal("part_time"), v.literal("intern"),
      v.literal("freelancer"), v.literal("consultant"),
    )),
    reportingManagerId: v.optional(v.id("employeeMaster")),
  },
  handler: async (ctx, args): Promise<PaginatedResponse<any>> => {
    const result = await paginatedQuery<any>(
      ctx,
      "employeeMaster",
      args,
      (q) => {
        if (args.status) return q.withIndex("by_status", (iq: any) => iq.eq("status", args.status!));
        if (args.departmentId) return q.withIndex("by_department", (iq: any) => iq.eq("departmentId", args.departmentId!));
        if (args.branchId) return q.withIndex("by_branch", (iq: any) => iq.eq("branchId", args.branchId!));
        if (args.companyId) return q.withIndex("by_company", (iq: any) => iq.eq("companyId", args.companyId!));
        return q.withIndex("by_createdAt").order("desc");
      },
    );

    let employees = result.items;
    if (args.employmentType) employees = employees.filter((e: any) => e.employmentType === args.employmentType);
    if (args.designationId) employees = employees.filter((e: any) => e.designationId === args.designationId);
    if (args.reportingManagerId) employees = employees.filter((e: any) => e.reportingManagerId === args.reportingManagerId);

    const personIds = [...new Set(employees.map((e: any) => e.personId).filter(Boolean))];
    const deptIds = [...new Set(employees.map((e: any) => e.departmentId).filter(Boolean))];
    const desigIds = [...new Set(employees.map((e: any) => e.designationId).filter(Boolean))];

    const [persons, departments, designations] = await Promise.all([
      batchGet<any>(ctx, personIds),
      batchGet<any>(ctx, deptIds),
      batchGet<any>(ctx, desigIds),
    ]);

    const personMap = new Map(persons.filter(Boolean).map((p: any) => [p._id, p]));
    const deptMap = new Map(departments.filter(Boolean).map((d: any) => [d._id, d]));
    const desigMap = new Map(designations.filter(Boolean).map((d: any) => [d._id, d]));

    const enriched = employees.map((emp: any) => {
      const person = personMap.get(emp.personId);
      const dept = deptMap.get(emp.departmentId);
      const desig = desigMap.get(emp.designationId);
      return {
        ...emp,
        personName: person?.displayName || `${person?.firstName || ""} ${person?.lastName || ""}`.trim() || "Unknown",
        departmentName: dept?.name || null,
        designationName: desig?.name || null,
      };
    });

    if (args.search) {
      const q = args.search.toLowerCase();
      enriched.filter((e: any) =>
        (e.personName && e.personName.toLowerCase().includes(q)) ||
        (e.employeeCode && e.employeeCode.toLowerCase().includes(q)),
      );
    }

    return { items: enriched, nextCursor: result.nextCursor, hasMore: result.hasMore };
  },
});

// ─── Get Employee Stats ──────────────────────────────────────────

export const getEmployeeStats = query({
  handler: async (ctx) => {
    const employees = await ctx.db.query("employeeMaster").collect();
    return {
      total: employees.length,
      active: employees.filter((e) => e.status === "active").length,
      onboarding: employees.filter((e) => e.status === "onboarding").length,
      probation: employees.filter((e) => e.status === "probation").length,
      suspended: employees.filter((e) => e.status === "suspended").length,
      resigned: employees.filter((e) => e.status === "resigned").length,
      terminated: employees.filter((e) => e.status === "terminated").length,
      retired: employees.filter((e) => e.status === "retired").length,
      archived: employees.filter((e) => e.status === "archived").length,
      permanent: employees.filter((e) => e.employmentType === "permanent").length,
      contract: employees.filter((e) => e.employmentType === "contract").length,
      partTime: employees.filter((e) => e.employmentType === "part_time").length,
      intern: employees.filter((e) => e.employmentType === "intern").length,
      freelancer: employees.filter((e) => e.employmentType === "freelancer").length,
      consultant: employees.filter((e) => e.employmentType === "consultant").length,
    };
  },
});
