import { v } from "convex/values";
import { mutation, query } from "./_generated/server";
import { getAuthUserId } from "@convex-dev/auth/server";
import { withScopeAndEvents } from "./withScopeAndEvents";

// ─── HELPERS ───────────────────────────────────────────────

async function createTimelineEvent(
  ctx: any,
  args: { studentId: string; eventType: string; title: string; description?: string; metadata?: string; performedBy?: string }
) {
  const performedBy = args.performedBy || (await getAuthUserId(ctx));
  await ctx.db.insert("studentEnrollmentHistory", {
    studentId: args.studentId,
    eventType: args.eventType,
    title: args.title,
    description: args.description,
    metadata: args.metadata,
    performedBy: performedBy,
    createdAt: Date.now(),
  });
}

function generateInvoiceNumber(prefix: string, serial: number): string {
  return `${prefix}-${String(serial).padStart(6, "0")}`;
}

// ─── AUTO-GENERATE INVOICES FROM INSTALLMENTS ──────────────

export const autoGenerateInvoiceFromInstallments = mutation({
  args: { token: v.optional(v.string()),
    studentId: v.id("studentMaster"),
    feeAccountId: v.id("studentFeeAccounts"),
    dueDate: v.number(),
    billingPeriod: v.optional(v.string()),
  },
  handler: withScopeAndEvents({ operation: "update", module: "finance", entity: "invoiceEngine" }, async (ctx, args) => {
    const userId = ctx.__performerUserId;
    if (!userId) throw new Error("Not authenticated");

    // Get unpaid installments
    const installments = await ctx.db.query("feeInstallments")
      .withIndex("studentId", (q: any) => q.eq("studentId", args.studentId))
      .filter((q: any) => q.neq(q.field("status"), "paid"))
      .order("asc")
      .collect();

    if (installments.length === 0) {
      throw new Error("No unpaid installments to invoice");
    }

    // Build line items from installments
    const lineItems = installments.map((inst: any, idx: number) => ({
      index: idx + 1,
      description: `Installment ${inst.installmentNumber} of ${inst.totalInstallments}`,
      amount: inst.amount,
      lateFee: inst.lateFee,
      total: inst.amount + (inst.lateFee || 0),
    }));

    const subtotal = lineItems.reduce((sum: number, item: any) => sum + item.amount, 0);
    const totalLateFee = lineItems.reduce((sum: number, item: any) => sum + (item.lateFee || 0), 0);
    const totalAmount = subtotal + totalLateFee;

    // Generate the invoice
    const allInvoices = await ctx.db.query("feeInvoices").collect();
    const invoiceNumber = generateInvoiceNumber("INV", allInvoices.length + 1);

    const invoiceId = await ctx.db.insert("feeInvoices", {
      invoiceNumber,
      studentId: args.studentId,
      feeAccountId: args.feeAccountId,
      invoiceDate: Date.now(),
      dueDate: args.dueDate,
      lineItems: JSON.stringify(lineItems),
      subtotal,
      discountAmount: 0,
      taxAmount: 0,
      totalAmount,
      paidAmount: 0,
      balanceDue: totalAmount,
      status: "pending",
      billingPeriod: args.billingPeriod,
      createdBy: userId,
    });

    // Link installments to this invoice
    for (const inst of installments) {
      await ctx.db.patch(inst._id, { invoiceId });
    }

    await createTimelineEvent(ctx, {
      studentId: args.studentId,
      eventType: "InvoiceAutoGenerated",
      title: "Invoice Auto-Generated",
      description: `Invoice ${invoiceNumber}: ${totalAmount} (${installments.length} installments)`,
      metadata: JSON.stringify({ invoiceId, invoiceNumber, installmentCount: installments.length, totalAmount }),
      performedBy: userId,
    });

    return { invoiceId, invoiceNumber, totalAmount, installmentCount: installments.length };
  }),
});

// ─── BATCH INVOICE GENERATION ──────────────────────────────

export const generateBatchInvoices = mutation({
  args: { token: v.optional(v.string()),
    studentIds: v.array(v.id("studentMaster")),
    dueDate: v.number(),
    billingPeriod: v.optional(v.string()),
  },
  handler: withScopeAndEvents({ operation: "create", module: "finance", entity: "invoiceEngine" }, async (ctx, args) => {
    const userId = ctx.__performerUserId;
    if (!userId) throw new Error("Not authenticated");

    const results: any[] = [];
    let serial = (await ctx.db.query("feeInvoices").collect()).length;

    for (const studentId of args.studentIds) {
      try {
        const account = await ctx.db.query("studentFeeAccounts")
          .withIndex("studentId", (q: any) => q.eq("studentId", studentId))
          .first();

        if (!account) {
          results.push({ studentId, status: "failed", reason: "No fee account found" });
          continue;
        }

        const installments = await ctx.db.query("feeInstallments")
          .withIndex("studentId", (q: any) => q.eq("studentId", studentId))
          .filter((q: any) => q.neq(q.field("status"), "paid"))
          .order("asc")
          .collect();

        if (installments.length === 0) {
          results.push({ studentId, status: "skipped", reason: "No unpaid installments" });
          continue;
        }

        serial++;
        const invoiceNumber = generateInvoiceNumber("INV", serial);
        const lineItems = installments.map((inst: any, idx: number) => ({
          index: idx + 1,
          description: `Installment ${inst.installmentNumber} of ${inst.totalInstallments}`,
          amount: inst.amount,
          lateFee: inst.lateFee,
          total: inst.amount + (inst.lateFee || 0),
        }));

        const subtotal = lineItems.reduce((sum: number, item: any) => sum + item.amount, 0);
        const totalLateFee = lineItems.reduce((sum: number, item: any) => sum + (item.lateFee || 0), 0);
        const totalAmount = subtotal + totalLateFee;

        const invoiceId = await ctx.db.insert("feeInvoices", {
          invoiceNumber,
          studentId,
          feeAccountId: account._id,
          invoiceDate: Date.now(),
          dueDate: args.dueDate,
          lineItems: JSON.stringify(lineItems),
          subtotal,
          discountAmount: 0,
          taxAmount: 0,
          totalAmount,
          paidAmount: 0,
          balanceDue: totalAmount,
          status: "pending",
          billingPeriod: args.billingPeriod,
          createdBy: userId,
        });

        for (const inst of installments) {
          await ctx.db.patch(inst._id, { invoiceId });
        }

        results.push({ studentId, status: "success", invoiceId, invoiceNumber, totalAmount });
      } catch (err: any) {
        results.push({ studentId, status: "failed", reason: err.message });
      }
    }

    return results;
  }),
});

// ─── GENERATE INVOICE FOR SPECIFIC INSTALLMENT ─────────────

export const generateInvoiceForInstallment = mutation({
  args: { token: v.optional(v.string()),
    studentId: v.id("studentMaster"),
    feeAccountId: v.id("studentFeeAccounts"),
    installmentId: v.id("feeInstallments"),
    dueDate: v.optional(v.number()),
  },
  handler: withScopeAndEvents({ operation: "create", module: "finance", entity: "invoiceEngine" }, async (ctx, args) => {
    const userId = ctx.__performerUserId;
    if (!userId) throw new Error("Not authenticated");

    const installment = await ctx.db.get(args.installmentId);
    if (!installment) throw new Error("Installment not found");

    const totalAmount = installment.amount + (installment.lateFee || 0);
    const lineItems = [{
      index: 1,
      description: `Installment ${installment.installmentNumber} of ${installment.totalInstallments}`,
      amount: installment.amount,
      lateFee: installment.lateFee,
      total: totalAmount,
    }];

    const allInvoices = await ctx.db.query("feeInvoices").collect();
    const invoiceNumber = generateInvoiceNumber("INV", allInvoices.length + 1);

    const invoiceId = await ctx.db.insert("feeInvoices", {
      invoiceNumber,
      studentId: args.studentId,
      feeAccountId: args.feeAccountId,
      invoiceDate: Date.now(),
      dueDate: args.dueDate || installment.dueDate,
      lineItems: JSON.stringify(lineItems),
      subtotal: installment.amount,
      discountAmount: 0,
      taxAmount: 0,
      totalAmount,
      paidAmount: 0,
      balanceDue: totalAmount,
      status: "pending",
      createdBy: userId,
    });

    // Link installment to invoice
    await ctx.db.patch(args.installmentId, { invoiceId });

    await createTimelineEvent(ctx, {
      studentId: args.studentId,
      eventType: "InstallmentInvoiceGenerated",
      title: "Installment Invoice Generated",
      description: `Invoice ${invoiceNumber} for installment ${installment.installmentNumber}`,
      metadata: JSON.stringify({ invoiceId, invoiceNumber, installmentNumber: installment.installmentNumber }),
      performedBy: userId,
    });

    return { invoiceId, invoiceNumber, totalAmount };
  }),
});

// ─── INVOICE DATA / TEMPLATE ───────────────────────────────

export const getInvoiceData = query({
  args: {
    invoiceId: v.id("feeInvoices"),
  },
  handler: async (ctx, args) => {
    const invoice = await ctx.db.get(args.invoiceId);
    if (!invoice) throw new Error("Invoice not found");

    const student = await ctx.db.get(invoice.studentId);
    if (!student) throw new Error("Student not found");

    const payments = await ctx.db.query("paymentTransactions")
      .withIndex("invoiceId", (q: any) => q.eq("invoiceId", args.invoiceId))
      .collect();

    const receipts = await ctx.db.query("receiptHistory")
      .filter((q: any) => q.eq(q.field("invoiceId"), args.invoiceId))
      .collect();

    let lineItems: any[] = [];
    try {
      lineItems = JSON.parse(invoice.lineItems);
    } catch { lineItems = []; }

    return {
      invoiceNumber: invoice.invoiceNumber,
      invoiceDate: new Date(invoice.invoiceDate).toLocaleDateString(),
      dueDate: new Date(invoice.dueDate).toLocaleDateString(),
      status: invoice.status,
      student: {
        name: `${student.firstName} ${student.lastName}`,
        admissionNumber: student.admissionNumber,
        rollNumber: student.rollNumber,
      },
      lineItems,
      subtotal: invoice.subtotal,
      discountAmount: invoice.discountAmount,
      taxAmount: invoice.taxAmount,
      totalAmount: invoice.totalAmount,
      paidAmount: invoice.paidAmount,
      balanceDue: invoice.balanceDue,
      payments: payments.map((p: any) => ({
        amount: p.amount,
        method: p.paymentMethod,
        date: new Date(p.paymentDate).toLocaleDateString(),
        status: p.status,
        transactionNumber: p.transactionNumber,
      })),
      receipts: receipts.map((r: any) => ({
        receiptNumber: r.receiptNumber,
        amount: r.amount,
        date: new Date(r.receiptDate).toLocaleDateString(),
      })),
    };
  },
});

// ─── INVOICE DASHBOARD ─────────────────────────────────────

export const getInvoiceDashboard = query({
  args: {
    status: v.optional(v.union(
      v.literal("draft"), v.literal("pending"), v.literal("paid"),
      v.literal("partial"), v.literal("overdue"), v.literal("cancelled"), v.literal("refunded")
    )),
  },
  handler: async (ctx, args) => {
    let query: any = ctx.db.query("feeInvoices");
    if (args.status) {
      query = query.withIndex("status", (q: any) => q.eq("status", args.status));
    }
    const invoices = await query.collect();

    const totalAmount = invoices.reduce((s: number, i: any) => s + i.totalAmount, 0);
    const totalPaid = invoices.reduce((s: number, i: any) => s + i.paidAmount, 0);
    const totalBalance = invoices.reduce((s: number, i: any) => s + i.balanceDue, 0);

    const groupedByStatus: Record<string, any[]> = {};
    for (const inv of invoices) {
      const status = inv.status;
      if (!groupedByStatus[status]) groupedByStatus[status] = [];
      groupedByStatus[status].push(inv);
    }

    const statusSummary = Object.entries(groupedByStatus).map(([status, items]: [string, any]) => ({
      status,
      count: items.length,
      total: items.reduce((s: number, i: any) => s + i.totalAmount, 0),
      paid: items.reduce((s: number, i: any) => s + i.paidAmount, 0),
      balance: items.reduce((s: number, i: any) => s + i.balanceDue, 0),
    }));

    return {
      summary: {
        totalInvoices: invoices.length,
        totalAmount,
        totalPaid,
        totalBalance,
        collectionRate: totalAmount > 0 ? Math.round((totalPaid / totalAmount) * 100) : 0,
      },
      statusSummary,
      overdueCount: invoices.filter((i: any) => i.status === "overdue").length,
      paidCount: invoices.filter((i: any) => i.status === "paid").length,
      pendingCount: invoices.filter((i: any) => i.status === "pending").length,
      cancelledCount: invoices.filter((i: any) => i.status === "cancelled").length,
    };
  },
});

// ─── FINANCIAL REPORTING ───────────────────────────────────

export const getFinancialReport = query({
  args: {
    startDate: v.optional(v.number()),
    endDate: v.optional(v.number()),
  },
  handler: async (ctx, args) => {
    let payments = await ctx.db.query("paymentTransactions")
      .filter((q: any) => q.neq(q.field("status"), "reversed"))
      .collect();

    let invoices = await ctx.db.query("feeInvoices")
      .filter((q: any) => q.neq(q.field("status"), "cancelled"))
      .collect();

    // Filter by date range if specified
    if (args.startDate) {
      payments = payments.filter((p: any) => p.paymentDate >= args.startDate!);
      invoices = invoices.filter((i: any) => i.invoiceDate >= args.startDate!);
    }
    if (args.endDate) {
      payments = payments.filter((p: any) => p.paymentDate <= args.endDate!);
      invoices = invoices.filter((i: any) => i.invoiceDate <= args.endDate!);
    }

    const totalRevenue = payments
      .filter((p: any) => p.status === "verified" || p.status === "completed")
      .reduce((s: number, p: any) => s + p.amount, 0);

    const pendingRevenue = invoices
      .filter((i: any) => i.status === "pending" || i.status === "partial")
      .reduce((s: number, i: any) => s + i.balanceDue, 0);

    const overdueRevenue = invoices
      .filter((i: any) => i.status === "overdue")
      .reduce((s: number, i: any) => s + i.balanceDue, 0);

    const totalRefunded = payments
      .filter((p: any) => p.status === "refunded")
      .reduce((s: number, p: any) => s + p.amount, 0);

    return {
      totalRevenue,
      pendingRevenue,
      overdueRevenue,
      totalRefunded,
      netRevenue: totalRevenue - totalRefunded,
      expectedRevenue: pendingRevenue + overdueRevenue,
      totalInvoiced: invoices.reduce((s: number, i: any) => s + i.totalAmount, 0),
      collectionRate: invoices.reduce((s: number, i: any) => s + i.totalAmount, 0) > 0
        ? Math.round((totalRevenue / invoices.reduce((s: number, i: any) => s + i.totalAmount, 0)) * 100)
        : 0,
    };
  },
});
