/**
 * Refund Engine — Enterprise-Integrated
 *
 * All mutations use withScopeAndEvents for complete enterprise adoption:
 *   ✓ ScopeEngine authorization    ✓ Event Pipeline
 *   ✓ Timeline auto-recording     ✓ Auto-document generation
 *   ✓ Notification Matrix routing  ✓ Workflow + Automation triggers
 *   ✓ Search indexing              ✓ Dashboard refresh signals
 */

import { v } from "convex/values";
import { mutation, query } from "./_generated/server";
import { getAuthUserId } from "@convex-dev/auth/server";
import { withScopeAndEvents, type ScopeAndEventsConfig } from "./withScopeAndEvents";
import { Id } from "./_generated/dataModel";

// ─── Enterprise Handler Factory ──────────────────────────────

function withRefund<P = any, R = any>(
  operation: ScopeAndEventsConfig<P, R>["operation"],
  entity: string,
  getScope: (args: P) => { companyId?: string; branchId?: string },
  handler: (ctx: any, args: P, userId: Id<"users">) => Promise<R>,
) {
  return async (ctx: any, args: P) => {
    const userId = await getAuthUserId(ctx);
    if (!userId) throw new Error("Not authenticated");
    const scope = getScope(args);
    const wrapped = withScopeAndEvents<P, R>(
      {
        operation,
        module: "finance",
        entity,
        getEntityCompanyId: () => scope.companyId,
        getEntityBranchId: () => scope.branchId,
        getUserId: () => userId as Id<"users">,
        notifyViaMatrix: true,
        triggerWorkflow: true,
        triggerAutomation: true,
        registerSearch: true,
        signalDashboard: true,
        autoGenerateDocs: [
          {
            documentType: "refund_voucher",
            contextBuilder: (a: any, r: any) => ({
              refundId: r?.toString() || "",
              studentId: a.studentId,
              amount: a.amount,
            }),
          },
        ],
      },
      (ctx2, args2) => handler(ctx2, args2, userId as Id<"users">),
    );
    return wrapped(ctx, args);
  };
}

// ─── CREATE REFUND REQUEST ───────────────────────────────

export const createRefundRequest = mutation({
  args: {
    token: v.optional(v.string()),
    studentId: v.optional(v.id("studentMaster")),
    transactionId: v.optional(v.id("paymentTransactions")),
    invoiceId: v.optional(v.id("feeInvoices")),
    amount: v.number(),
    reason: v.string(),
    reasonCategory: v.union(v.literal("academic"), v.literal("administrative"), v.literal("financial"), v.literal("withdrawal"), v.literal("other")),
    notes: v.optional(v.string()),
    companyId: v.optional(v.id("companies")),
    branchId: v.optional(v.id("branches")),
  },
  handler: withRefund("create", "refund_request", (a) => ({
    companyId: a.companyId,
    branchId: a.branchId,
  }), async (ctx, args, userId) => {
    const { companyId, branchId, ...rest } = args;
    return ctx.db.insert("refundRequests", {
      ...rest,
      status: "draft",
      createdBy: userId,
      createdAt: Date.now(),
      updatedAt: Date.now(),
    });
  }),
});

// ─── SUBMIT FOR APPROVAL ─────────────────────────────────

export const submitRefundForApproval = mutation({
  args: {
    token: v.optional(v.string()),
    id: v.id("refundRequests"),
    companyId: v.optional(v.id("companies")),
    branchId: v.optional(v.id("branches")),
  },
  handler: withRefund("update", "refund_submit", (a) => ({
    companyId: a.companyId,
    branchId: a.branchId,
  }), async (ctx, args) => {
    const request = await ctx.db.get(args.id);
    if (!request) throw new Error("Refund request not found");
    if (request.status !== "draft") throw new Error("Only draft refunds can be submitted");
    await ctx.db.patch(args.id, { status: "pending", updatedAt: Date.now() });
    return args.id;
  }),
});

// ─── APPROVE / REJECT ────────────────────────────────────

export const approveRefund = mutation({
  args: {
    token: v.optional(v.string()),
    id: v.id("refundRequests"),
    approve: v.boolean(),
    notes: v.optional(v.string()),
    companyId: v.optional(v.id("companies")),
    branchId: v.optional(v.id("branches")),
  },
  handler: withRefund("approve", "refund_decision", (a) => ({
    companyId: a.companyId,
    branchId: a.branchId,
  }), async (ctx, args, userId) => {
    const request = await ctx.db.get(args.id);
    if (!request) throw new Error("Refund request not found");
    if (request.status !== "pending") throw new Error("Refund is not pending approval");

    await ctx.db.patch(args.id, {
      status: args.approve ? "approved" : "rejected",
      approvedBy: userId,
      approvedAt: Date.now(),
      notes: args.notes || request.notes,
      updatedAt: Date.now(),
    });
    return args.id;
  }),
});

// ─── PROCESS REFUND ──────────────────────────────────────

export const processRefund = mutation({
  args: {
    token: v.optional(v.string()),
    id: v.id("refundRequests"),
    refundMethod: v.string(),
    refundReference: v.optional(v.string()),
    companyId: v.optional(v.id("companies")),
    branchId: v.optional(v.id("branches")),
  },
  handler: withRefund("update", "refund_process", (a) => ({
    companyId: a.companyId,
    branchId: a.branchId,
  }), async (ctx, args) => {
    const request = await ctx.db.get(args.id);
    if (!request) throw new Error("Refund request not found");
    if (request.status !== "approved") throw new Error("Refund must be approved before processing");

    await ctx.db.patch(args.id, {
      status: "processing",
      refundMethod: args.refundMethod,
      refundReference: args.refundReference,
      processedAt: Date.now(),
      updatedAt: Date.now(),
    });
    return args.id;
  }),
});

// ─── COMPLETE REFUND ─────────────────────────────────────

export const completeRefund = mutation({
  args: {
    token: v.optional(v.string()),
    id: v.id("refundRequests"),
    notes: v.optional(v.string()),
    companyId: v.optional(v.id("companies")),
    branchId: v.optional(v.id("branches")),
  },
  handler: withRefund("update", "refund_complete", (a) => ({
    companyId: a.companyId,
    branchId: a.branchId,
  }), async (ctx, args) => {
    const request = await ctx.db.get(args.id);
    if (!request) throw new Error("Refund request not found");
    await ctx.db.patch(args.id, {
      status: "completed",
      notes: args.notes || request.notes,
      updatedAt: Date.now(),
    });
    return args.id;
  }),
});

// ─── QUERIES ─────────────────────────────────────────────

export const listRefundRequests = query({
  args: {
    status: v.optional(v.union(v.literal("draft"), v.literal("pending"), v.literal("approved"), v.literal("rejected"), v.literal("processing"), v.literal("completed"))),
    studentId: v.optional(v.id("studentMaster")),
  },
  handler: async (ctx, args) => {
    const userId = await getAuthUserId(ctx);
    let q: any = ctx.db.query("refundRequests");
    if (args.studentId) q = q.withIndex("studentId", (q2: any) => q2.eq("studentId", args.studentId));
    if (args.status) q = q.filter((q2: any) => q2.eq(q2.field("status"), args.status));
    const results = await q.order("desc").collect();
    if (userId) {
      const { ScopeEngine } = await import("./scopeEngine");
      const scope = await ScopeEngine.forUser(ctx, userId);
      return scope.filterByScope(results);
    }
    return results;
  },
});

export const getRefundRequest = query({
  args: { id: v.id("refundRequests") },
  handler: async (ctx, args) => ctx.db.get(args.id),
});

export const getRefundSummary = query({
  args: { startDate: v.optional(v.number()), endDate: v.optional(v.number()) },
  handler: async (ctx, args) => {
    const userId = await getAuthUserId(ctx);
    let requests = await ctx.db.query("refundRequests").collect();
    if (userId) {
      const { ScopeEngine } = await import("./scopeEngine");
      const scope = await ScopeEngine.forUser(ctx, userId);
      requests = scope.filterByScope(requests);
    }
    if (args.startDate) requests = requests.filter((r: any) => r.createdAt >= args.startDate!);
    if (args.endDate) requests = requests.filter((r: any) => r.createdAt <= args.endDate!);

    return {
      totalCount: requests.length,
      totalRequested: requests.reduce((s: number, r: any) => s + r.amount, 0),
      totalApproved: requests.filter((r: any) => r.status === "approved" || r.status === "processing" || r.status === "completed")
        .reduce((s: number, r: any) => s + r.amount, 0),
      totalCompleted: requests.filter((r: any) => r.status === "completed").reduce((s: number, r: any) => s + r.amount, 0),
      totalRejected: requests.filter((r: any) => r.status === "rejected").reduce((s: number, r: any) => s + r.amount, 0),
      pendingCount: requests.filter((r: any) => r.status === "pending").length,
      approvedCount: requests.filter((r: any) => r.status === "approved" || r.status === "processing" || r.status === "completed").length,
      completedCount: requests.filter((r: any) => r.status === "completed").length,
    };
  },
});
