/**
 * Unified Scope + Events Middleware — Adoption Accelerator
 *
 * Combines ScopeEngine authorization + EventPipeline event wiring + auto-document
 * generation into a SINGLE wrapper for any Convex mutation handler.
 *
 * Instead of:
 *   const scope = await ScopeEngine.forUser(ctx, userId);
 *   if (!scope.canWrite(entity)) throw new Error("Forbidden");
 *   const result = await myHandler(ctx, args);
 *   await withEventPipeline(config, myHandler)(ctx, args);
 *
 * Just do:
 *   export const myMutation = mutation({
 *     args: { ... },
 *     handler: withScopeAndEvents(config, myHandler),
 *   });
 *
 * This reduces boilerplate and ensures NO module bypasses scope or events.
 */

import { v } from "convex/values";
import { mutation, query } from "./_generated/server";
import { Doc, Id } from "./_generated/dataModel";
import { ScopeEngine } from "./scopeEngine";
import { withEventPipeline, EventPipelineConfig, MutationContext, MutationResult, extractIdFromResult } from "../platform/eventPipeline";

// ─── Unified Config ─────────────────────────────────────────

export interface ScopeAndEventsConfig<P = any, R = any> {
  // Which operation
  operation: "create" | "read" | "update" | "delete" | "approve";

  // Module and entity for event pipeline
  module: string;
  entity: string;
  eventType?: string;
  title?: string;

  // Scope: how to extract entity scope from args for the permission check
  // Before the handler runs, we check canWrite/canDelete against these.
  getEntityCompanyId?: (args: P) => string | undefined;
  getEntityBranchId?: (args: P) => string | undefined;
  getEntityDepartmentId?: (args: P) => string | undefined;

  // User ID extraction (for event pipeline)
  getUserId?: (args: P) => Id<"users"> | undefined;

  // Event pipeline config (auto-built if omitted)
  eventConfig?: Partial<EventPipelineConfig<P, R>>;

  // Auto-generate documents after mutation (optional)
  autoGenerateDocs?: Array<{
    documentType: "fee_receipt" | "bounce_notice" | "penalty_letter" | "settlement_letter" |
                  "offer_letter" | "consent_form" | "refund_voucher" | "credit_note" |
                  "admission_form" | "id_card" | "gst_invoice";
    contextBuilder: (args: P, result: R) => Record<string, unknown>;
  }>;

  // Notify via notification matrix (optional)
  notifyViaMatrix?: boolean;
}

// ─── Unified Handler Factory ────────────────────────────────

export function withScopeAndEvents<P extends Record<string, unknown>, R extends MutationResult>(
  config: ScopeAndEventsConfig<P, R>,
  handler: (ctx: MutationContext, args: P) => Promise<R>,
): (ctx: MutationContext, args: P) => Promise<R> {
  return async (ctx: MutationContext, args: P) => {
    // ── 1. Resolve performer ──────────────────────────
    const userId = config.getUserId?.(args);
    let scope: ScopeEngine | null = null;

    if (userId) {
      scope = await ScopeEngine.forUser(ctx as any, userId as Id<"users">);
    }

    // ── 2. Build entity scope object ───────────────────
    const entityScope = {
      companyId: config.getEntityCompanyId?.(args),
      branchId: config.getEntityBranchId?.(args),
      departmentId: config.getEntityDepartmentId?.(args),
    };

    // ── 3. Scope check (before handler) ────────────────
    if (scope) {
      let allowed = true;
      switch (config.operation) {
        case "create":
        case "update":
          allowed = scope.canWrite(entityScope);
          break;
        case "delete":
          allowed = scope.canDelete(entityScope);
          break;
        case "approve":
          allowed = scope.canApprove(entityScope);
          break;
        case "read":
          allowed = scope.canRead(entityScope);
          break;
      }
      if (!allowed) {
        throw new Error(
          `Scope denied: User ${userId} cannot ${config.operation} ${config.module}.${config.entity}` +
          ` in scope (company:${entityScope.companyId || "any"}, branch:${entityScope.branchId || "any"})`
        );
      }
    }

    // ── 4. Execute business logic ──────────────────────
    const result = await handler(ctx, args);

    // ── 5. Publish events via Event Pipeline ───────────
    try {
      const entityId = extractIdFromResult(result);
      const performedBy = userId;
      const now = Date.now();
      const eventType = config.eventType || `${config.module}.${config.entity}.${config.operation}`;
      const title = config.title || `${config.module}.${config.entity}.${config.operation}`;

      // Audit log
      await ctx.db.insert("auditLogs", {
        action: config.operation,
        entity: config.entity,
        entityId: entityId || "",
        userId: performedBy,
        companyId: entityScope.companyId,
        branchId: entityScope.branchId,
        departmentId: entityScope.departmentId,
        createdAt: now,
      });

      // Timeline event
      if (entityId) {
        await ctx.db.insert("timelineEvents", {
          module: config.module,
          eventType,
          entityType: config.entity,
          entityId,
          title,
          description: title,
          performedBy,
          companyId: entityScope.companyId,
          branchId: entityScope.branchId,
          departmentId: entityScope.departmentId,
          createdAt: now,
        });
      }

      // Event bus
      if (entityId) {
        await ctx.db.insert("events", {
          module: config.module,
          eventType,
          entityType: config.entity,
          entityId,
          performedBy,
          companyId: entityScope.companyId,
          branchId: entityScope.branchId,
          departmentId: entityScope.departmentId,
          status: "published",
          publishedAt: now,
          createdAt: now,
        });
      }

      // ── 6. Auto-generate documents (if configured) ───
      if (config.autoGenerateDocs && entityId) {
        for (const docConfig of config.autoGenerateDocs) {
          try {
            const docContext = docConfig.contextBuilder(args, result);
            await ctx.db.insert("documentGenerationQueue", {
              documentType: docConfig.documentType,
              entityType: config.entity,
              entityId,
              context: JSON.stringify(docContext),
              companyId: entityScope.companyId,
              branchId: entityScope.branchId,
              status: "pending",
              createdAt: now,
            });
          } catch (e) {
            // Document generation enqueue failure should never break main operation
            console.error(`[ScopeAndEvents] Failed to enqueue document ${docConfig.documentType}:`, e);
          }
        }
      }

      // ── 7. Notification matrix (if enabled) ──────────
      if (config.notifyViaMatrix && entityId) {
        try {
          // Record a notification trigger event for the notification matrix
          await ctx.db.insert("events", {
            module: "notification",
            eventType: `notification.${config.module}.${config.entity}.${config.operation}`,
            entityType: config.entity,
            entityId,
            performedBy,
            companyId: entityScope.companyId,
            branchId: entityScope.branchId,
            status: "triggered",
            publishedAt: now,
            createdAt: now,
          });
        } catch {}
      }

      // ── 8. Trigger Automation Engine ─────────────────
      if (entityId) {
        try {
          await ctx.db.insert("events", {
            module: "automation",
            eventType: `automation.trigger.${eventType}`,
            entityType: config.entity,
            entityId,
            performedBy,
            companyId: entityScope.companyId,
            branchId: entityScope.branchId,
            status: "triggered",
            publishedAt: now,
            createdAt: now,
          });
        } catch {}
      }
    } catch (error) {
      // Event pipeline failure must never break the business operation
      console.error(`[ScopeAndEvents] Failed to record events for ${config.module}.${config.entity}:`, error);
    }

    return result;
  };
}

// ─── Convenience Builders ───────────────────────────────────

interface ScopeArgs {
  companyId?: string;
  branchId?: string;
  departmentId?: string;
  createdBy?: string;
}

/**
 * Build scope extractors from a typical entity args object.
 * Expects args to have companyId, branchId, departmentId fields.
 */
export function scopeFromArgs<P extends ScopeArgs>() {
  return {
    getEntityCompanyId: (args: P) => args.companyId,
    getEntityBranchId: (args: P) => args.branchId,
    getEntityDepartmentId: (args: P) => args.departmentId,
  };
}

/**
 * Build a document generation config for auto-generating receipts on payment.
 */
export function docOnPayment<P extends { studentId?: string; amount?: number; receiptNumber?: string }, R>() {
  return [{
    documentType: "fee_receipt" as const,
    contextBuilder: (args: P, result: R) => ({
      studentId: args.studentId,
      amount: args.amount,
      receiptNumber: args.receiptNumber || extractIdFromResult(result as any),
      paymentMode: (args as any).paymentMode || "unknown",
      generatedAt: new Date().toISOString(),
    }),
  }];
}

/**
 * Build auto-doc config for bounce notices.
 */
export function docOnBounce<P extends { studentId?: string; chequeNumber?: string; bounceReason?: string; penaltyAmount?: number }, R>() {
  return [{
    documentType: "bounce_notice" as const,
    contextBuilder: (args: P) => ({
      studentId: args.studentId,
      chequeNumber: args.chequeNumber,
      bounceReason: args.bounceReason,
      penaltyAmount: args.penaltyAmount,
      generatedAt: new Date().toISOString(),
    }),
  }];
}

// ─── Scope-Enforcing Query Wrapper ──────────────────────────

/**
 * For queries: wraps a query handler with ScopeEngine read-check.
 * Throws if user cannot read the specified entity scope.
 */
export function withScopeCheck<P extends { userId?: Id<"users"> } & Record<string, unknown>, R>(
  operation: "read" | "admin",
  getEntityScope: (args: P) => { companyId?: string; branchId?: string; departmentId?: string },
  handler: (ctx: MutationContext, args: P) => Promise<R>,
): (ctx: MutationContext, args: P) => Promise<R> {
  return async (ctx: MutationContext, args: P) => {
    const userId = args.userId;
    if (userId) {
      const scope = await ScopeEngine.forUser(ctx as any, userId);
      const entityScope = getEntityScope(args);
      const allowed = operation === "admin"
        ? scope.accessLevel(entityScope) === "admin"
        : scope.canRead(entityScope);

      if (!allowed) {
        throw new Error(`Scope denied: User cannot ${operation} this entity`);
      }
    }
    return handler(ctx, args);
  };
}
