/**
 * Unified Enterprise Pipeline (v2) — Complete Adoption Accelerator
 *
 * Combines EVERY enterprise integration into ONE wrapper:
 *   1. ScopeEngine authorization
 *   2. Event Pipeline (130+ event types)
 *   3. Timeline auto-recording
 *   4. Audit auto-logging
 *   5. Notification Matrix routing
 *   6. Auto-Document Generation
 *   7. Workflow Engine triggers
 *   8. Automation Engine triggers
 *   9. Search Index auto-registration
 *  10. Dashboard Refresh signals
 *
 * Usage:
 *   export const myMutation = mutation({
 *     args: { ... },
 *     handler: withScopeAndEvents(config, myHandler),
 *   });
 *
 * This ensures NO module bypasses ANY enterprise integration.
 */

import { v } from "convex/values";
import { mutation, query } from "./_generated/server";
import { Doc, Id } from "./_generated/dataModel";
import { ScopeEngine } from "./scopeEngine";
import { withEventPipeline, EventPipelineConfig, MutationContext, MutationResult, extractIdFromResult } from "../platform/eventPipeline";
import { indexEntity } from "./autoSearchIndexer";

// ─── Unified Config ─────────────────────────────────────────

export type DocumentType =
  | "fee_receipt" | "gst_invoice" | "credit_note" | "debit_note" | "refund_voucher" | "payment_voucher"
  | "bounce_notice" | "penalty_letter" | "settlement_letter"
  | "admission_form" | "id_card" | "consent_form"
  | "offer_letter" | "appointment_letter" | "confirmation_letter" | "promotion_letter"
  | "relieving_letter" | "experience_letter" | "salary_slip"
  | "hall_ticket" | "admit_card" | "bonafide" | "leaving_certificate" | "transfer_certificate" | "marksheet"
  | "service_report" | "stock_issue" | "goods_receipt" | "rfq" | "quotation" | "purchase_order";

// ─── Unified Config ─────────────────────────────────────────

export interface ScopeAndEventsConfig<P = any, R = any> {
  operation: "create" | "read" | "update" | "delete" | "approve";
  module: string;
  entity: string;
  eventType?: string;
  title?: string;
  getEntityCompanyId?: (args: P) => string | undefined;
  getEntityBranchId?: (args: P) => string | undefined;
  getEntityDepartmentId?: (args: P) => string | undefined;
  getUserId?: (args: P) => Id<"users"> | undefined;
  eventConfig?: Partial<EventPipelineConfig<P, R>>;

  // Auto-document generation
  autoGenerateDocs?: Array<{
    documentType: DocumentType;
    contextBuilder: (args: P, result: R) => Record<string, unknown>;
  }>;

  // Enterprise features (all default to true when enabled)
  notifyViaMatrix?: boolean;
  triggerWorkflow?: boolean;
  triggerAutomation?: boolean;
  registerSearch?: boolean;
  signalDashboard?: boolean;
}

// ─── Unified Handler Factory ────────────────────────────────

export function withScopeAndEvents<P extends Record<string, unknown>, R extends MutationResult>(
  config: ScopeAndEventsConfig<P, R>,
  handler: (ctx: MutationContext, args: P) => Promise<R>,
): (ctx: MutationContext, args: P) => Promise<R> {
  return async (ctx: MutationContext, args: P) => {
    const userId = config.getUserId?.(args);
    let scope: ScopeEngine | null = null;

    if (userId) {
      scope = await ScopeEngine.forUser(ctx as any, userId as Id<"users">);
    }

    const entityScope = {
      companyId: config.getEntityCompanyId?.(args),
      branchId: config.getEntityBranchId?.(args),
      departmentId: config.getEntityDepartmentId?.(args),
    };

    // ── Scope check ───────────────────────────────────┐
    if (scope) {
      let allowed = true;
      switch (config.operation) {
        case "create":
        case "update":
          allowed = scope.canWrite(entityScope); break;
        case "delete":
          allowed = scope.canDelete(entityScope); break;
        case "approve":
          allowed = scope.canApprove(entityScope); break;
        case "read":
          allowed = scope.canRead(entityScope); break;
      }
      if (!allowed) {
        throw new Error(
          `Scope denied: User ${userId} cannot ${config.operation} ${config.module}.${config.entity}` +
          ` in scope (company:${entityScope.companyId || "any"}, branch:${entityScope.branchId || "any"})`
        );
      }
    }

    // ── Execute business logic ─────────────────────────┐
    const result = await handler(ctx, args);

    // ── Post-operation enterprise pipeline ─────────────┐
    try {
      const entityId = extractIdFromResult(result);
      const performedBy = userId;
      const now = Date.now();
      const eventType = config.eventType || `${config.module}.${config.entity}.${config.operation}`;
      const title = config.title || `${config.module}.${config.entity}.${config.operation}`;

      // 1. Audit log
      await ctx.db.insert("auditLogs", {
        action: config.operation,
        entity: config.entity,
        entityId: entityId || "",
        userId: performedBy,
        companyId: entityScope.companyId,
        branchId: entityScope.branchId,
        departmentId: entityScope.departmentId,
        createdAt: now,
      });

      // 2. Timeline event
      if (entityId) {
        await ctx.db.insert("timelineEvents", {
          module: config.module,
          eventType,
          entityType: config.entity,
          entityId,
          title,
          description: title,
          performedBy,
          companyId: entityScope.companyId,
          branchId: entityScope.branchId,
          departmentId: entityScope.departmentId,
          createdAt: now,
        });
      }

      // 3. Event bus (central event stream)
      if (entityId) {
        await ctx.db.insert("events", {
          module: config.module,
          eventType,
          entityType: config.entity,
          entityId,
          performedBy,
          companyId: entityScope.companyId,
          branchId: entityScope.branchId,
          departmentId: entityScope.departmentId,
          status: "published",
          publishedAt: now,
          createdAt: now,
        });
      }

      // 4. Auto-document generation
      if (config.autoGenerateDocs && entityId) {
        for (const docConfig of config.autoGenerateDocs) {
          try {
            const docContext = docConfig.contextBuilder(args, result);
            await ctx.db.insert("documentGenerationQueue", {
              documentType: docConfig.documentType,
              entityType: config.entity,
              entityId,
              context: JSON.stringify(docContext),
              companyId: entityScope.companyId,
              branchId: entityScope.branchId,
              status: "pending",
              createdAt: now,
            });
          } catch (e) {
            console.error(`[Pipeline] Doc gen failed for ${docConfig.documentType}:`, e);
          }
        }
      }

      // 5. Notification Matrix trigger
      if (config.notifyViaMatrix !== false && entityId) {
        try {
          await ctx.db.insert("events", {
            module: "notification",
            eventType: `notification.${config.module}.${config.entity}.${config.operation}`,
            entityType: config.entity,
            entityId,
            performedBy,
            companyId: entityScope.companyId,
            branchId: entityScope.branchId,
            status: "triggered",
            publishedAt: now,
            createdAt: now,
          });
        } catch {}
      }

      // 6. Workflow trigger (new — Phase 1)
      if (config.triggerWorkflow !== false && entityId) {
        try {
          await ctx.db.insert("events", {
            module: "workflow",
            eventType: `workflow.trigger.${eventType}`,
            entityType: config.entity,
            entityId,
            performedBy,
            companyId: entityScope.companyId,
            branchId: entityScope.branchId,
            status: "triggered",
            publishedAt: now,
            createdAt: now,
          });
        } catch {}
      }

      // 7. Automation trigger (new — Phase 2)
      if (config.triggerAutomation !== false && entityId) {
        try {
          await ctx.db.insert("events", {
            module: "automation",
            eventType: `automation.trigger.${eventType}`,
            entityType: config.entity,
            entityId,
            performedBy,
            companyId: entityScope.companyId,
            branchId: entityScope.branchId,
            status: "triggered",
            publishedAt: now,
            createdAt: now,
          });
        } catch {}
      }

      // 8. Search index registration (new — Phase 7)
      if (config.registerSearch !== false && entityId) {
        try {
          const titleStr = typeof title === "string" ? title : String(title);
          await indexEntity(ctx as any, {
            entityType: config.entity,
            entityId,
            title: titleStr,
            keywords: [config.module, config.entity, config.operation, titleStr],
            module: config.module,
            companyId: entityScope.companyId,
            branchId: entityScope.branchId,
            createdBy: performedBy,
          });
        } catch {}
      }

      // 9. Dashboard refresh signal (new — Phase 6)
      if (config.signalDashboard !== false) {
        try {
          const key = `${config.module}_${config.entity}`;
          const existing = await ctx.db.query("dashboardRefreshSignals")
            .withIndex("module_entity", (q: any) => q.eq("module", config.module).eq("entity", config.entity))
            .first();
          if (existing) {
            await ctx.db.patch(existing._id, { lastRefresh: now, updatedAt: now });
          } else {
            await ctx.db.insert("dashboardRefreshSignals", {
              module: config.module,
              entity: config.entity,
              lastRefresh: now,
              createdAt: now,
              updatedAt: now,
            });
          }
        } catch {}
      }

    } catch (error) {
      // Pipeline failure must NEVER break the business operation
      console.error(`[EnterprisePipeline] Failed for ${config.module}.${config.entity}:`, error);
    }

    return result;
  };
}

// ─── Convenience Builders ───────────────────────────────────

interface ScopeArgs {
  companyId?: string;
  branchId?: string;
  departmentId?: string;
  createdBy?: string;
}

export function scopeFromArgs<P extends ScopeArgs>() {
  return {
    getEntityCompanyId: (args: P) => args.companyId,
    getEntityBranchId: (args: P) => args.branchId,
    getEntityDepartmentId: (args: P) => args.departmentId,
  };
}

// ─── Scope-Enforcing Query Wrapper ──────────────────────────

export function withScopeCheck<P extends { userId?: Id<"users"> } & Record<string, unknown>, R>(
  operation: "read" | "admin",
  getEntityScope: (args: P) => { companyId?: string; branchId?: string; departmentId?: string },
  handler: (ctx: MutationContext, args: P) => Promise<R>,
): (ctx: MutationContext, args: P) => Promise<R> {
  return async (ctx: MutationContext, args: P) => {
    const userId = args.userId;
    if (userId) {
      const scope = await ScopeEngine.forUser(ctx as any, userId);
      const entityScope = getEntityScope(args);
      const allowed = operation === "admin"
        ? scope.accessLevel(entityScope) === "admin"
        : scope.canRead(entityScope);
      if (!allowed) {
        throw new Error(`Scope denied: User cannot ${operation} this entity`);
      }
    }
    return handler(ctx, args);
  };
}
