/**
 * Minimal type declarations for Convex generated modules.
 *
 * These modules are generated by `npx convex dev` and live in `src/convex/_generated/`.
 * The frontend tsconfig excludes `src/convex`, so we declare the module types here
 * to satisfy the TypeScript compiler at type-check time.
 *
 * At runtime, Vite resolves these through the Convex plugin.
 */
declare module "@convex/_generated/api" {
  export const api: any;
  export const internal: any;
}
declare module "@convex/_generated/dataModel" {
  export type TableNames = string;
  export type Doc<T extends string> = Record<string, unknown> & {
    _id: string;
    _creationTime: number;
  };
  export type Id<T extends string> = string;
  export type SystemTableNames = string;
}
