/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as academicBatchTypes from "../academicBatchTypes.js";
import type * as academicBatches from "../academicBatches.js";
import type * as academicBoards from "../academicBoards.js";
import type * as academicClassrooms from "../academicClassrooms.js";
import type * as academicLanguages from "../academicLanguages.js";
import type * as academicMediums from "../academicMediums.js";
import type * as academicPrograms from "../academicPrograms.js";
import type * as academicSections from "../academicSections.js";
import type * as academicSemesters from "../academicSemesters.js";
import type * as academicSessions from "../academicSessions.js";
import type * as academicStreams from "../academicStreams.js";
import type * as academicSubVerticals from "../academicSubVerticals.js";
import type * as academicSubjects from "../academicSubjects.js";
import type * as academicTerms from "../academicTerms.js";
import type * as academicVerticals from "../academicVerticals.js";
import type * as accessEngine from "../accessEngine.js";
import type * as actionPermissions from "../actionPermissions.js";
import type * as addressEngine from "../addressEngine.js";
import type * as adminEngine from "../adminEngine.js";
import type * as admissionEngine from "../admissionEngine.js";
import type * as adoptionHelpers from "../adoptionHelpers.js";
import type * as aiRuntimeEngine from "../aiRuntimeEngine.js";
import type * as alumniEngine from "../alumniEngine.js";
import type * as analyticsEngine from "../analyticsEngine.js";
import type * as approvals from "../approvals.js";
import type * as assessmentFramework from "../assessmentFramework.js";
import type * as assetEngine from "../assetEngine.js";
import type * as assignmentEngine from "../assignmentEngine.js";
import type * as attendanceEngine from "../attendanceEngine.js";
import type * as auth from "../auth.js";
import type * as auth_emailOtp from "../auth/emailOtp.js";
import type * as authHelpers from "../authHelpers.js";
import type * as autoSearchIndexer from "../autoSearchIndexer.js";
import type * as automationEngine from "../automationEngine.js";
import type * as bankReconciliationEngine from "../bankReconciliationEngine.js";
import type * as billingEngine from "../billingEngine.js";
import type * as boardRulesEngine from "../boardRulesEngine.js";
import type * as boostEnterpriseSimulation from "../boostEnterpriseSimulation.js";
import type * as budgetEngine from "../budgetEngine.js";
import type * as businessRulesEngine from "../businessRulesEngine.js";
import type * as candidateEngine from "../candidateEngine.js";
import type * as certificateEngine from "../certificateEngine.js";
import type * as chartOfAccountsEngine from "../chartOfAccountsEngine.js";
import type * as chequeEngine from "../chequeEngine.js";
import type * as collectionEngine from "../collectionEngine.js";
import type * as commEmailTemplates from "../commEmailTemplates.js";
import type * as commNotificationTypes from "../commNotificationTypes.js";
import type * as commSmsTemplates from "../commSmsTemplates.js";
import type * as commWhatsAppTemplates from "../commWhatsAppTemplates.js";
import type * as communicationCampaignEngine from "../communicationCampaignEngine.js";
import type * as communicationHub from "../communicationHub.js";
import type * as configurationStudioEngine from "../configurationStudioEngine.js";
import type * as consentEngine from "../consentEngine.js";
import type * as contactEngine from "../contactEngine.js";
import type * as costCenterEngine from "../costCenterEngine.js";
import type * as crm from "../crm.js";
import type * as crmActivity from "../crmActivity.js";
import type * as crmApprovals from "../crmApprovals.js";
import type * as crmCalls from "../crmCalls.js";
import type * as crmCampaignChannels from "../crmCampaignChannels.js";
import type * as crmCampaignTypes from "../crmCampaignTypes.js";
import type * as crmCounsellingOutcomes from "../crmCounsellingOutcomes.js";
import type * as crmCounsellingTypes from "../crmCounsellingTypes.js";
import type * as crmCourses from "../crmCourses.js";
import type * as crmDashboard from "../crmDashboard.js";
import type * as crmDiscounts from "../crmDiscounts.js";
import type * as crmDocuments from "../crmDocuments.js";
import type * as crmEnquiryTypes from "../crmEnquiryTypes.js";
import type * as crmFollowUpOutcomes from "../crmFollowUpOutcomes.js";
import type * as crmFollowUpTypes from "../crmFollowUpTypes.js";
import type * as crmHelpers from "../crmHelpers.js";
import type * as crmIndustries from "../crmIndustries.js";
import type * as crmLeadCategories from "../crmLeadCategories.js";
import type * as crmLeadQualification from "../crmLeadQualification.js";
import type * as crmLeadScoringRules from "../crmLeadScoringRules.js";
import type * as crmLeads from "../crmLeads.js";
import type * as crmLostReasons from "../crmLostReasons.js";
import type * as crmMarketingChannels from "../crmMarketingChannels.js";
import type * as crmNotes from "../crmNotes.js";
import type * as crmPayments from "../crmPayments.js";
import type * as crmPriorities from "../crmPriorities.js";
import type * as crmReferralSources from "../crmReferralSources.js";
import type * as crmSales from "../crmSales.js";
import type * as crmSources from "../crmSources.js";
import type * as crmStages from "../crmStages.js";
import type * as crmTags from "../crmTags.js";
import type * as crmTasks from "../crmTasks.js";
import type * as crmUtmCampaigns from "../crmUtmCampaigns.js";
import type * as crmUtmMediums from "../crmUtmMediums.js";
import type * as crmUtmSources from "../crmUtmSources.js";
import type * as crmWhatsApp from "../crmWhatsApp.js";
import type * as dashboard from "../dashboard.js";
import type * as dashboardEngine from "../dashboardEngine.js";
import type * as dashboardLiveRefresh from "../dashboardLiveRefresh.js";
import type * as dashboardProviders from "../dashboardProviders.js";
import type * as demo_auth from "../demo/auth.js";
import type * as demo_data from "../demo/data.js";
import type * as demo_queries from "../demo/queries.js";
import type * as demo_seed from "../demo/seed.js";
import type * as documentAutoGeneration from "../documentAutoGeneration.js";
import type * as documentEngine from "../documentEngine.js";
import type * as documentTemplateEngine from "../documentTemplateEngine.js";
import type * as emailEngine from "../emailEngine.js";
import type * as emergencyContactEngine from "../emergencyContactEngine.js";
import type * as employeeEngine from "../employeeEngine.js";
import type * as employeeLifecycle from "../employeeLifecycle.js";
import type * as employeeSearch from "../employeeSearch.js";
import type * as engines_accessControlEngine from "../engines/accessControlEngine.js";
import type * as engines_activityEngine from "../engines/activityEngine.js";
import type * as engines_attachmentEngine from "../engines/attachmentEngine.js";
import type * as engines_auditEngine from "../engines/auditEngine.js";
import type * as engines_commentEngine from "../engines/commentEngine.js";
import type * as engines_notificationEngine from "../engines/notificationEngine.js";
import type * as engines_seedEngine from "../engines/seedEngine.js";
import type * as engines_sequenceEngine from "../engines/sequenceEngine.js";
import type * as engines_timelineEngine from "../engines/timelineEngine.js";
import type * as enrollmentEngine from "../enrollmentEngine.js";
import type * as enterpriseSimulation from "../enterpriseSimulation.js";
import type * as enterpriseValidation from "../enterpriseValidation.js";
import type * as entityEngine from "../entityEngine.js";
import type * as eventRegistry from "../eventRegistry.js";
import type * as examEngine from "../examEngine.js";
import type * as examEnterpriseAnalytics from "../examEnterpriseAnalytics.js";
import type * as examIncidentEngine from "../examIncidentEngine.js";
import type * as executiveReports from "../executiveReports.js";
import type * as exitEngine from "../exitEngine.js";
import type * as expenseEngine from "../expenseEngine.js";
import type * as facultyEngine from "../facultyEngine.js";
import type * as feeEngine from "../feeEngine.js";
import type * as fieldSecurity from "../fieldSecurity.js";
import type * as financeBankAccounts from "../financeBankAccounts.js";
import type * as financeCurrencies from "../financeCurrencies.js";
import type * as financeDiscountCategories from "../financeDiscountCategories.js";
import type * as financeEngine from "../financeEngine.js";
import type * as financeExpenseCategories from "../financeExpenseCategories.js";
import type * as financeFeeCategories from "../financeFeeCategories.js";
import type * as financeFinancialYears from "../financeFinancialYears.js";
import type * as financeGstRates from "../financeGstRates.js";
import type * as financeIncomeCategories from "../financeIncomeCategories.js";
import type * as financePaymentModes from "../financePaymentModes.js";
import type * as financePlatform from "../financePlatform.js";
import type * as financeReports from "../financeReports.js";
import type * as financeTaxTypes from "../financeTaxTypes.js";
import type * as financialClosingEngine from "../financialClosingEngine.js";
import type * as financialTransactionEngine from "../financialTransactionEngine.js";
import type * as fixedAssetEngine from "../fixedAssetEngine.js";
import type * as formEngine from "../formEngine.js";
import type * as github from "../github.js";
import type * as governanceEngine from "../governanceEngine.js";
import type * as gridEngine from "../gridEngine.js";
import type * as gstComplianceEngine from "../gstComplianceEngine.js";
import type * as hrDocumentTypes from "../hrDocumentTypes.js";
import type * as hrEmployeeCategories from "../hrEmployeeCategories.js";
import type * as hrEmployeeTypes from "../hrEmployeeTypes.js";
import type * as hrEmploymentStatuses from "../hrEmploymentStatuses.js";
import type * as hrExperienceLevels from "../hrExperienceLevels.js";
import type * as hrSkills from "../hrSkills.js";
import type * as hrWorkLocations from "../hrWorkLocations.js";
import type * as http from "../http.js";
import type * as intakeEngine from "../intakeEngine.js";
import type * as integrationEngine from "../integrationEngine.js";
import type * as integrations_github from "../integrations/github.js";
import type * as integrations_openai from "../integrations/openai.js";
import type * as interviewEngine from "../interviewEngine.js";
import type * as inventoryBranchEngine from "../inventoryBranchEngine.js";
import type * as inventoryEngine from "../inventoryEngine.js";
import type * as invoiceEngine from "../invoiceEngine.js";
import type * as knowledgeEngine from "../knowledgeEngine.js";
import type * as kpiEngine from "../kpiEngine.js";
import type * as leadActivityEngine from "../leadActivityEngine.js";
import type * as leadCommunicationEngine from "../leadCommunicationEngine.js";
import type * as leadConversionEngine from "../leadConversionEngine.js";
import type * as leadHealthEngine from "../leadHealthEngine.js";
import type * as leadLifecycle from "../leadLifecycle.js";
import type * as leadMeetingEngine from "../leadMeetingEngine.js";
import type * as leaveEngine from "../leaveEngine.js";
import type * as lmsEngine from "../lmsEngine.js";
import type * as lmsFacultyEngine from "../lmsFacultyEngine.js";
import type * as lmsPlatform from "../lmsPlatform.js";
import type * as lmsStudentEngine from "../lmsStudentEngine.js";
import type * as marksEngine from "../marksEngine.js";
import type * as menuEngine from "../menuEngine.js";
import type * as messenger from "../messenger.js";
import type * as metadataRegistry from "../metadataRegistry.js";
import type * as moduleActivationEngine from "../moduleActivationEngine.js";
import type * as notificationMatrix from "../notificationMatrix.js";
import type * as notifications from "../notifications.js";
import type * as offerEngine from "../offerEngine.js";
import type * as onboardingEngine from "../onboardingEngine.js";
import type * as opportunities from "../opportunities.js";
import type * as organization from "../organization.js";
import type * as organization_branches from "../organization/branches.js";
import type * as organization_departments from "../organization/departments.js";
import type * as organization_organizations from "../organization/organizations.js";
import type * as organization_teams from "../organization/teams.js";
import type * as organizationBranches from "../organizationBranches.js";
import type * as organizationCompanies from "../organizationCompanies.js";
import type * as organizationDepartments from "../organizationDepartments.js";
import type * as organizationDesignations from "../organizationDesignations.js";
import type * as organizationTeams from "../organizationTeams.js";
import type * as paymentEngine from "../paymentEngine.js";
import type * as payrollEngine from "../payrollEngine.js";
import type * as pdcLegalEngine from "../pdcLegalEngine.js";
import type * as performanceEngine from "../performanceEngine.js";
import type * as personEngine from "../personEngine.js";
import type * as personQRCode from "../personQRCode.js";
import type * as personSearch from "../personSearch.js";
import type * as procurementEngine from "../procurementEngine.js";
import type * as procurementPlatform from "../procurementPlatform.js";
import type * as profileEngine from "../profileEngine.js";
import type * as promotionEngine from "../promotionEngine.js";
import type * as pushEngine from "../pushEngine.js";
import type * as queryHelpers from "../queryHelpers.js";
import type * as queryPlatform from "../queryPlatform.js";
import type * as questionPaperEngine from "../questionPaperEngine.js";
import type * as quotations from "../quotations.js";
import type * as receiptEngine from "../receiptEngine.js";
import type * as receiptTemplateEngine from "../receiptTemplateEngine.js";
import type * as recordScope from "../recordScope.js";
import type * as recruitmentEngine from "../recruitmentEngine.js";
import type * as refundCalcEngine from "../refundCalcEngine.js";
import type * as refundEngine from "../refundEngine.js";
import type * as relationshipEngine from "../relationshipEngine.js";
import type * as reportCardEngine from "../reportCardEngine.js";
import type * as reportDesignerEngine from "../reportDesignerEngine.js";
import type * as reportEngine from "../reportEngine.js";
import type * as reportExportEngine from "../reportExportEngine.js";
import type * as reportScheduleEngine from "../reportScheduleEngine.js";
import type * as resultEngine from "../resultEngine.js";
import type * as revaluationEngine from "../revaluationEngine.js";
import type * as ruleRuntimeEngine from "../ruleRuntimeEngine.js";
import type * as runtimeObservability from "../runtimeObservability.js";
import type * as salesInvoiceTypes from "../salesInvoiceTypes.js";
import type * as salesOpportunityStages from "../salesOpportunityStages.js";
import type * as salesOpportunityTypes from "../salesOpportunityTypes.js";
import type * as salesPaymentStatuses from "../salesPaymentStatuses.js";
import type * as salesPerformance from "../salesPerformance.js";
import type * as salesQuotationStatuses from "../salesQuotationStatuses.js";
import type * as salesTaxSlabs from "../salesTaxSlabs.js";
import type * as salesTerritories from "../salesTerritories.js";
import type * as schema_academic from "../schema/academic.js";
import type * as schema_accessControl from "../schema/accessControl.js";
import type * as schema_analytics from "../schema/analytics.js";
import type * as schema_calendar from "../schema/calendar.js";
import type * as schema_communication from "../schema/communication.js";
import type * as schema_crm from "../schema/crm.js";
import type * as schema_documents from "../schema/documents.js";
import type * as schema_dynamicMenus from "../schema/dynamicMenus.js";
import type * as schema_enterprise from "../schema/enterprise.js";
import type * as schema_examination from "../schema/examination.js";
import type * as schema_finance from "../schema/finance.js";
import type * as schema_forms from "../schema/forms.js";
import type * as schema_hr from "../schema/hr.js";
import type * as schema_lms from "../schema/lms.js";
import type * as schema_metadata from "../schema/metadata.js";
import type * as schema_organization from "../schema/organization.js";
import type * as schema_people from "../schema/people.js";
import type * as schema_procurement from "../schema/procurement.js";
import type * as schema_scheduling from "../schema/scheduling.js";
import type * as schema_shared from "../schema/shared.js";
import type * as schema_student from "../schema/student.js";
import type * as schema_support from "../schema/support.js";
import type * as schema_tasks from "../schema/tasks.js";
import type * as schema_workflow from "../schema/workflow.js";
import type * as scopeEngine from "../scopeEngine.js";
import type * as searchEngine from "../searchEngine.js";
import type * as searchEngineV2 from "../searchEngineV2.js";
import type * as searchPlatform from "../searchPlatform.js";
import type * as securityPolicies from "../securityPolicies.js";
import type * as seed from "../seed.js";
import type * as seedSupplementalData from "../seedSupplementalData.js";
import type * as slaEngine from "../slaEngine.js";
import type * as smsEngine from "../smsEngine.js";
import type * as studentEngine from "../studentEngine.js";
import type * as studentLifecycle from "../studentLifecycle.js";
import type * as studentSearch from "../studentSearch.js";
import type * as tasks from "../tasks.js";
import type * as taxEngine from "../taxEngine.js";
import type * as teacherSchedulingEngine from "../teacherSchedulingEngine.js";
import type * as templateEngine from "../templateEngine.js";
import type * as timelineEngine from "../timelineEngine.js";
import type * as userManagement from "../userManagement.js";
import type * as users from "../users.js";
import type * as verification from "../verification.js";
import type * as visibilityEngine from "../visibilityEngine.js";
import type * as whatsappEngine from "../whatsappEngine.js";
import type * as whiteLabelEngine from "../whiteLabelEngine.js";
import type * as withScopeAndEvents from "../withScopeAndEvents.js";
import type * as workflowEngine from "../workflowEngine.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  academicBatchTypes: typeof academicBatchTypes;
  academicBatches: typeof academicBatches;
  academicBoards: typeof academicBoards;
  academicClassrooms: typeof academicClassrooms;
  academicLanguages: typeof academicLanguages;
  academicMediums: typeof academicMediums;
  academicPrograms: typeof academicPrograms;
  academicSections: typeof academicSections;
  academicSemesters: typeof academicSemesters;
  academicSessions: typeof academicSessions;
  academicStreams: typeof academicStreams;
  academicSubVerticals: typeof academicSubVerticals;
  academicSubjects: typeof academicSubjects;
  academicTerms: typeof academicTerms;
  academicVerticals: typeof academicVerticals;
  accessEngine: typeof accessEngine;
  actionPermissions: typeof actionPermissions;
  addressEngine: typeof addressEngine;
  adminEngine: typeof adminEngine;
  admissionEngine: typeof admissionEngine;
  adoptionHelpers: typeof adoptionHelpers;
  aiRuntimeEngine: typeof aiRuntimeEngine;
  alumniEngine: typeof alumniEngine;
  analyticsEngine: typeof analyticsEngine;
  approvals: typeof approvals;
  assessmentFramework: typeof assessmentFramework;
  assetEngine: typeof assetEngine;
  assignmentEngine: typeof assignmentEngine;
  attendanceEngine: typeof attendanceEngine;
  auth: typeof auth;
  "auth/emailOtp": typeof auth_emailOtp;
  authHelpers: typeof authHelpers;
  autoSearchIndexer: typeof autoSearchIndexer;
  automationEngine: typeof automationEngine;
  bankReconciliationEngine: typeof bankReconciliationEngine;
  billingEngine: typeof billingEngine;
  boardRulesEngine: typeof boardRulesEngine;
  boostEnterpriseSimulation: typeof boostEnterpriseSimulation;
  budgetEngine: typeof budgetEngine;
  businessRulesEngine: typeof businessRulesEngine;
  candidateEngine: typeof candidateEngine;
  certificateEngine: typeof certificateEngine;
  chartOfAccountsEngine: typeof chartOfAccountsEngine;
  chequeEngine: typeof chequeEngine;
  collectionEngine: typeof collectionEngine;
  commEmailTemplates: typeof commEmailTemplates;
  commNotificationTypes: typeof commNotificationTypes;
  commSmsTemplates: typeof commSmsTemplates;
  commWhatsAppTemplates: typeof commWhatsAppTemplates;
  communicationCampaignEngine: typeof communicationCampaignEngine;
  communicationHub: typeof communicationHub;
  configurationStudioEngine: typeof configurationStudioEngine;
  consentEngine: typeof consentEngine;
  contactEngine: typeof contactEngine;
  costCenterEngine: typeof costCenterEngine;
  crm: typeof crm;
  crmActivity: typeof crmActivity;
  crmApprovals: typeof crmApprovals;
  crmCalls: typeof crmCalls;
  crmCampaignChannels: typeof crmCampaignChannels;
  crmCampaignTypes: typeof crmCampaignTypes;
  crmCounsellingOutcomes: typeof crmCounsellingOutcomes;
  crmCounsellingTypes: typeof crmCounsellingTypes;
  crmCourses: typeof crmCourses;
  crmDashboard: typeof crmDashboard;
  crmDiscounts: typeof crmDiscounts;
  crmDocuments: typeof crmDocuments;
  crmEnquiryTypes: typeof crmEnquiryTypes;
  crmFollowUpOutcomes: typeof crmFollowUpOutcomes;
  crmFollowUpTypes: typeof crmFollowUpTypes;
  crmHelpers: typeof crmHelpers;
  crmIndustries: typeof crmIndustries;
  crmLeadCategories: typeof crmLeadCategories;
  crmLeadQualification: typeof crmLeadQualification;
  crmLeadScoringRules: typeof crmLeadScoringRules;
  crmLeads: typeof crmLeads;
  crmLostReasons: typeof crmLostReasons;
  crmMarketingChannels: typeof crmMarketingChannels;
  crmNotes: typeof crmNotes;
  crmPayments: typeof crmPayments;
  crmPriorities: typeof crmPriorities;
  crmReferralSources: typeof crmReferralSources;
  crmSales: typeof crmSales;
  crmSources: typeof crmSources;
  crmStages: typeof crmStages;
  crmTags: typeof crmTags;
  crmTasks: typeof crmTasks;
  crmUtmCampaigns: typeof crmUtmCampaigns;
  crmUtmMediums: typeof crmUtmMediums;
  crmUtmSources: typeof crmUtmSources;
  crmWhatsApp: typeof crmWhatsApp;
  dashboard: typeof dashboard;
  dashboardEngine: typeof dashboardEngine;
  dashboardLiveRefresh: typeof dashboardLiveRefresh;
  dashboardProviders: typeof dashboardProviders;
  "demo/auth": typeof demo_auth;
  "demo/data": typeof demo_data;
  "demo/queries": typeof demo_queries;
  "demo/seed": typeof demo_seed;
  documentAutoGeneration: typeof documentAutoGeneration;
  documentEngine: typeof documentEngine;
  documentTemplateEngine: typeof documentTemplateEngine;
  emailEngine: typeof emailEngine;
  emergencyContactEngine: typeof emergencyContactEngine;
  employeeEngine: typeof employeeEngine;
  employeeLifecycle: typeof employeeLifecycle;
  employeeSearch: typeof employeeSearch;
  "engines/accessControlEngine": typeof engines_accessControlEngine;
  "engines/activityEngine": typeof engines_activityEngine;
  "engines/attachmentEngine": typeof engines_attachmentEngine;
  "engines/auditEngine": typeof engines_auditEngine;
  "engines/commentEngine": typeof engines_commentEngine;
  "engines/notificationEngine": typeof engines_notificationEngine;
  "engines/seedEngine": typeof engines_seedEngine;
  "engines/sequenceEngine": typeof engines_sequenceEngine;
  "engines/timelineEngine": typeof engines_timelineEngine;
  enrollmentEngine: typeof enrollmentEngine;
  enterpriseSimulation: typeof enterpriseSimulation;
  enterpriseValidation: typeof enterpriseValidation;
  entityEngine: typeof entityEngine;
  eventRegistry: typeof eventRegistry;
  examEngine: typeof examEngine;
  examEnterpriseAnalytics: typeof examEnterpriseAnalytics;
  examIncidentEngine: typeof examIncidentEngine;
  executiveReports: typeof executiveReports;
  exitEngine: typeof exitEngine;
  expenseEngine: typeof expenseEngine;
  facultyEngine: typeof facultyEngine;
  feeEngine: typeof feeEngine;
  fieldSecurity: typeof fieldSecurity;
  financeBankAccounts: typeof financeBankAccounts;
  financeCurrencies: typeof financeCurrencies;
  financeDiscountCategories: typeof financeDiscountCategories;
  financeEngine: typeof financeEngine;
  financeExpenseCategories: typeof financeExpenseCategories;
  financeFeeCategories: typeof financeFeeCategories;
  financeFinancialYears: typeof financeFinancialYears;
  financeGstRates: typeof financeGstRates;
  financeIncomeCategories: typeof financeIncomeCategories;
  financePaymentModes: typeof financePaymentModes;
  financePlatform: typeof financePlatform;
  financeReports: typeof financeReports;
  financeTaxTypes: typeof financeTaxTypes;
  financialClosingEngine: typeof financialClosingEngine;
  financialTransactionEngine: typeof financialTransactionEngine;
  fixedAssetEngine: typeof fixedAssetEngine;
  formEngine: typeof formEngine;
  github: typeof github;
  governanceEngine: typeof governanceEngine;
  gridEngine: typeof gridEngine;
  gstComplianceEngine: typeof gstComplianceEngine;
  hrDocumentTypes: typeof hrDocumentTypes;
  hrEmployeeCategories: typeof hrEmployeeCategories;
  hrEmployeeTypes: typeof hrEmployeeTypes;
  hrEmploymentStatuses: typeof hrEmploymentStatuses;
  hrExperienceLevels: typeof hrExperienceLevels;
  hrSkills: typeof hrSkills;
  hrWorkLocations: typeof hrWorkLocations;
  http: typeof http;
  intakeEngine: typeof intakeEngine;
  integrationEngine: typeof integrationEngine;
  "integrations/github": typeof integrations_github;
  "integrations/openai": typeof integrations_openai;
  interviewEngine: typeof interviewEngine;
  inventoryBranchEngine: typeof inventoryBranchEngine;
  inventoryEngine: typeof inventoryEngine;
  invoiceEngine: typeof invoiceEngine;
  knowledgeEngine: typeof knowledgeEngine;
  kpiEngine: typeof kpiEngine;
  leadActivityEngine: typeof leadActivityEngine;
  leadCommunicationEngine: typeof leadCommunicationEngine;
  leadConversionEngine: typeof leadConversionEngine;
  leadHealthEngine: typeof leadHealthEngine;
  leadLifecycle: typeof leadLifecycle;
  leadMeetingEngine: typeof leadMeetingEngine;
  leaveEngine: typeof leaveEngine;
  lmsEngine: typeof lmsEngine;
  lmsFacultyEngine: typeof lmsFacultyEngine;
  lmsPlatform: typeof lmsPlatform;
  lmsStudentEngine: typeof lmsStudentEngine;
  marksEngine: typeof marksEngine;
  menuEngine: typeof menuEngine;
  messenger: typeof messenger;
  metadataRegistry: typeof metadataRegistry;
  moduleActivationEngine: typeof moduleActivationEngine;
  notificationMatrix: typeof notificationMatrix;
  notifications: typeof notifications;
  offerEngine: typeof offerEngine;
  onboardingEngine: typeof onboardingEngine;
  opportunities: typeof opportunities;
  organization: typeof organization;
  "organization/branches": typeof organization_branches;
  "organization/departments": typeof organization_departments;
  "organization/organizations": typeof organization_organizations;
  "organization/teams": typeof organization_teams;
  organizationBranches: typeof organizationBranches;
  organizationCompanies: typeof organizationCompanies;
  organizationDepartments: typeof organizationDepartments;
  organizationDesignations: typeof organizationDesignations;
  organizationTeams: typeof organizationTeams;
  paymentEngine: typeof paymentEngine;
  payrollEngine: typeof payrollEngine;
  pdcLegalEngine: typeof pdcLegalEngine;
  performanceEngine: typeof performanceEngine;
  personEngine: typeof personEngine;
  personQRCode: typeof personQRCode;
  personSearch: typeof personSearch;
  procurementEngine: typeof procurementEngine;
  procurementPlatform: typeof procurementPlatform;
  profileEngine: typeof profileEngine;
  promotionEngine: typeof promotionEngine;
  pushEngine: typeof pushEngine;
  queryHelpers: typeof queryHelpers;
  queryPlatform: typeof queryPlatform;
  questionPaperEngine: typeof questionPaperEngine;
  quotations: typeof quotations;
  receiptEngine: typeof receiptEngine;
  receiptTemplateEngine: typeof receiptTemplateEngine;
  recordScope: typeof recordScope;
  recruitmentEngine: typeof recruitmentEngine;
  refundCalcEngine: typeof refundCalcEngine;
  refundEngine: typeof refundEngine;
  relationshipEngine: typeof relationshipEngine;
  reportCardEngine: typeof reportCardEngine;
  reportDesignerEngine: typeof reportDesignerEngine;
  reportEngine: typeof reportEngine;
  reportExportEngine: typeof reportExportEngine;
  reportScheduleEngine: typeof reportScheduleEngine;
  resultEngine: typeof resultEngine;
  revaluationEngine: typeof revaluationEngine;
  ruleRuntimeEngine: typeof ruleRuntimeEngine;
  runtimeObservability: typeof runtimeObservability;
  salesInvoiceTypes: typeof salesInvoiceTypes;
  salesOpportunityStages: typeof salesOpportunityStages;
  salesOpportunityTypes: typeof salesOpportunityTypes;
  salesPaymentStatuses: typeof salesPaymentStatuses;
  salesPerformance: typeof salesPerformance;
  salesQuotationStatuses: typeof salesQuotationStatuses;
  salesTaxSlabs: typeof salesTaxSlabs;
  salesTerritories: typeof salesTerritories;
  "schema/academic": typeof schema_academic;
  "schema/accessControl": typeof schema_accessControl;
  "schema/analytics": typeof schema_analytics;
  "schema/calendar": typeof schema_calendar;
  "schema/communication": typeof schema_communication;
  "schema/crm": typeof schema_crm;
  "schema/documents": typeof schema_documents;
  "schema/dynamicMenus": typeof schema_dynamicMenus;
  "schema/enterprise": typeof schema_enterprise;
  "schema/examination": typeof schema_examination;
  "schema/finance": typeof schema_finance;
  "schema/forms": typeof schema_forms;
  "schema/hr": typeof schema_hr;
  "schema/lms": typeof schema_lms;
  "schema/metadata": typeof schema_metadata;
  "schema/organization": typeof schema_organization;
  "schema/people": typeof schema_people;
  "schema/procurement": typeof schema_procurement;
  "schema/scheduling": typeof schema_scheduling;
  "schema/shared": typeof schema_shared;
  "schema/student": typeof schema_student;
  "schema/support": typeof schema_support;
  "schema/tasks": typeof schema_tasks;
  "schema/workflow": typeof schema_workflow;
  scopeEngine: typeof scopeEngine;
  searchEngine: typeof searchEngine;
  searchEngineV2: typeof searchEngineV2;
  searchPlatform: typeof searchPlatform;
  securityPolicies: typeof securityPolicies;
  seed: typeof seed;
  seedSupplementalData: typeof seedSupplementalData;
  slaEngine: typeof slaEngine;
  smsEngine: typeof smsEngine;
  studentEngine: typeof studentEngine;
  studentLifecycle: typeof studentLifecycle;
  studentSearch: typeof studentSearch;
  tasks: typeof tasks;
  taxEngine: typeof taxEngine;
  teacherSchedulingEngine: typeof teacherSchedulingEngine;
  templateEngine: typeof templateEngine;
  timelineEngine: typeof timelineEngine;
  userManagement: typeof userManagement;
  users: typeof users;
  verification: typeof verification;
  visibilityEngine: typeof visibilityEngine;
  whatsappEngine: typeof whatsappEngine;
  whiteLabelEngine: typeof whiteLabelEngine;
  withScopeAndEvents: typeof withScopeAndEvents;
  workflowEngine: typeof workflowEngine;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {};
